import type { DimensionAnalysisPayload } from '@/store/agentTypes'

export const DOC_INTELLIGENCE_DIMENSIONS: DimensionAnalysisPayload = {
  tileId: 'doc-intelligence',
  agentName: 'Document Intelligence Agent',
  taskDimensions: [
    {
      id: 'doci-task-document-classification',
      label: 'Document Classification',
      description: 'Identify and categorize document type (invoice, receipt, statement, contract)',
      parentTaskId: 'report-generation',
      intentCategories: ['categorization', 'type-detection', 'metadata-extraction'],
      confidence: 'high',
    },
    {
      id: 'doci-task-field-extraction',
      label: 'Field Extraction',
      description: 'Extract structured fields from unstructured documents (dates, amounts, vendors)',
      parentTaskId: 'invoice-comparison',
      intentCategories: ['data-extraction', 'ocr-processing', 'field-mapping'],
      confidence: 'high',
    },
    {
      id: 'doci-task-invoice-parsing',
      label: 'Invoice Parsing',
      description: 'Parse line items, totals, tax calculations, and payment terms from invoices',
      parentTaskId: 'invoice-comparison',
      intentCategories: ['line-item-extraction', 'financial-parsing', 'amount-calculation'],
      confidence: 'high',
    },
    {
      id: 'doci-task-cost-aggregation',
      label: 'Cost Aggregation',
      description: 'Aggregate costs across multiple invoices by vendor, service, or category',
      parentTaskId: 'cost-analysis',
      intentCategories: ['aggregation', 'cost-rollup', 'financial-analysis'],
      confidence: 'high',
    },
    {
      id: 'doci-task-anomaly-detection',
      label: 'Anomaly Detection',
      description: 'Identify unusual patterns, outliers, or inconsistencies in document data',
      parentTaskId: 'cost-analysis',
      intentCategories: ['outlier-detection', 'quality-check', 'fraud-prevention'],
      confidence: 'medium',
    },
    {
      id: 'doci-task-cross-reference-validation',
      label: 'Cross-Reference Validation',
      description: 'Validate document data against templates, prior records, and external sources',
      parentTaskId: 'invoice-comparison',
      intentCategories: ['validation', 'reconciliation', 'data-verification'],
      confidence: 'medium',
    },
    {
      id: 'doci-task-compliance-checking',
      label: 'Compliance Checking',
      description: 'Verify documents meet regulatory, contractual, and organizational standards',
      parentTaskId: 'report-generation',
      intentCategories: ['compliance-verification', 'policy-check', 'audit-readiness'],
      confidence: 'medium',
    },
    {
      id: 'doci-task-template-matching',
      label: 'Template Matching',
      description: 'Match document layout and structure against predefined invoice templates',
      parentTaskId: 'invoice-comparison',
      intentCategories: ['template-detection', 'format-recognition', 'vendor-identification'],
      confidence: 'medium',
    },
    {
      id: 'doci-task-risk-flagging',
      label: 'Risk Flagging',
      description: 'Flag documents with potential payment risks, duplicate entries, or discrepancies',
      parentTaskId: 'cost-analysis',
      intentCategories: ['risk-assessment', 'error-flagging', 'threshold-detection'],
      confidence: 'low',
    },
    {
      id: 'doci-task-report-formatting',
      label: 'Report Formatting',
      description: 'Generate formatted reports and summaries from extracted document data',
      parentTaskId: 'report-generation',
      intentCategories: ['report-generation', 'formatting', 'summary-creation'],
      confidence: 'low',
    },
  ],
  dataDimensions: [
    {
      id: 'doci-data-aws-invoice',
      label: 'AWS Invoice Data',
      depthScore: 4,
      subTopics: [
        { name: 'Service charges', depth: 4 },
        { name: 'Usage metrics', depth: 3 },
        { name: 'Reserved instance discounts', depth: 3 },
        { name: 'Regional pricing', depth: 2 },
      ],
      keyEntities: ['compute', 'storage', 'networking', 'support-plans', 'tax-allocation'],
      connectedDomains: ['cloud-infrastructure', 'cost-management', 'vendor-billing'],
      sourceAttribution: [
        { sourceId: 'aws-invoice', sourceName: 'AWS_Invoice_Jan.pdf', count: '47' },
      ],
      gapNote: 'Missing detailed discount breakdowns for multi-year commitments',
    },
    {
      id: 'doci-data-gcp-invoice',
      label: 'GCP Invoice Data',
      depthScore: 4,
      subTopics: [
        { name: 'Compute engine billing', depth: 4 },
        { name: 'Data transfer costs', depth: 3 },
        { name: 'Commitment discounts', depth: 3 },
        { name: 'Machine learning services', depth: 2 },
      ],
      keyEntities: ['gce-instances', 'bigquery', 'cloud-storage', 'sustained-use', 'commitment-level'],
      connectedDomains: ['cloud-infrastructure', 'analytics-platform', 'cost-optimization'],
      sourceAttribution: [
        { sourceId: 'gcp-invoice', sourceName: 'GCP_Invoice_Jan.pdf', count: '52' },
      ],
      gapNote: 'Lacks granular breakdown of per-project costs for multi-tenant setups',
    },
    {
      id: 'doci-data-azure-invoice',
      label: 'Azure Invoice Data',
      depthScore: 4,
      subTopics: [
        { name: 'Virtual machine charges', depth: 4 },
        { name: 'Database services', depth: 3 },
        { name: 'Hybrid benefit credits', depth: 3 },
        { name: 'Enterprise agreement terms', depth: 2 },
      ],
      keyEntities: ['vm-sizing', 'sql-database', 'app-service', 'hybrid-benefits', 'ea-discounts'],
      connectedDomains: ['cloud-infrastructure', 'microsoft-ecosystem', 'licensing-management'],
      sourceAttribution: [
        { sourceId: 'azure-invoice', sourceName: 'Azure_Invoice_Jan.pdf', count: '61' },
      ],
      gapNote: 'Enterprise agreement pricing not fully itemized for comparative analysis',
    },
    {
      id: 'doci-data-invoice-template',
      label: 'Invoice Template Schema',
      depthScore: 3,
      subTopics: [
        { name: 'Standard field mappings', depth: 3 },
        { name: 'Validation rules', depth: 3 },
        { name: 'Vendor-specific variations', depth: 2 },
        { name: 'Regulatory requirements', depth: 2 },
      ],
      keyEntities: ['invoice-number', 'po-reference', 'payment-terms', 'tax-id', 'currency-code'],
      connectedDomains: ['document-standards', 'financial-processes', 'compliance-framework'],
      sourceAttribution: [
        { sourceId: 'invoice-template', sourceName: 'Invoice_Template.xlsx', count: '15' },
      ],
    },
  ],
  userProfileDimensions: [
    {
      id: 'doci-up-system-user',
      label: 'System User',
      description: 'API-first automation user for batch processing and system integration',
      contextAxis: 'programmatic-integration',
      postureAxis: 'efficiency-focused',
      channelAxis: 'api-webhook',
      behaviorImpact: 'Requires high-accuracy extraction with minimal human review overhead',
    },
    {
      id: 'doci-up-business-user',
      label: 'Business User',
      description: 'Finance manager tracking spend across multiple cloud providers',
      contextAxis: 'cost-accountability',
      postureAxis: 'risk-averse',
      channelAxis: 'web-dashboard',
      behaviorImpact: 'Demands exception-driven alerts and year-over-year trend analysis',
    },
    {
      id: 'doci-up-end-user',
      label: 'End User',
      description: 'Department head needing cost breakdowns by project or team',
      contextAxis: 'resource-allocation',
      postureAxis: 'decision-support',
      channelAxis: 'email-report',
      behaviorImpact: 'Expects plain-language summaries and actionable spend reduction recommendations',
    },
    {
      id: 'doci-up-auditor',
      label: 'Auditor',
      description: 'Third-party or internal audit professional verifying compliance and accuracy',
      contextAxis: 'regulatory-compliance',
      postureAxis: 'verification-focused',
      channelAxis: 'audit-trail-export',
      behaviorImpact: 'Requires complete lineage, reconciliation support, and variance documentation',
    },
    {
      id: 'doci-up-analyst',
      label: 'Analyst',
      description: 'Data analyst performing deep-dive cost engineering and optimization',
      contextAxis: 'optimization-focus',
      postureAxis: 'analytical-precision',
      channelAxis: 'data-export',
      behaviorImpact: 'Needs granular data exports, custom metrics, and predictive modeling inputs',
    },
    {
      id: 'doci-up-procurement',
      label: 'Procurement Officer',
      description: 'Responsible for vendor contract negotiations and cost validation',
      contextAxis: 'vendor-management',
      postureAxis: 'negotiation-focused',
      channelAxis: 'comparison-report',
      behaviorImpact: 'Seeks competitive benchmarking data and invoice discrepancy alerts for contract disputes',
    },
  ],
  summaryText: 'The Document Intelligence Agent analyzes multi-cloud invoices (AWS, GCP, Azure) to extract costs, detect anomalies, and ensure compliance through intelligent field extraction and template matching. It serves finance, audit, and procurement teams with automated cost aggregation, risk flagging, and formatted reporting across heterogeneous vendor billing formats.',
}

export const DECISION_WORKFLOW_DIMENSIONS: DimensionAnalysisPayload = {
  tileId: 'decision-workflow',
  agentName: 'Decision Workflow Agent',
  taskDimensions: [
    {
      id: 'dw-task-appointment-scheduling',
      label: 'Appointment Scheduling',
      description: 'Check dentist availability and book appointments based on patient preferences and clinical needs',
      parentTaskId: 'schedule-appointments',
      intentCategories: ['availability-check', 'booking', 'calendar-management'],
      confidence: 'high',
    },
    {
      id: 'dw-task-insurance-verification',
      label: 'Insurance Verification',
      description: 'Validate patient insurance coverage, eligibility, and benefits before treatment',
      parentTaskId: 'check-insurance',
      intentCategories: ['coverage-check', 'eligibility-verification', 'benefits-lookup'],
      confidence: 'high',
    },
    {
      id: 'dw-task-clinical-triage',
      label: 'Clinical Triage',
      description: 'Assess patient symptoms and determine urgency level (routine, urgent, emergency)',
      parentTaskId: 'answer-patient-questions',
      intentCategories: ['severity-assessment', 'condition-classification', 'routing-logic'],
      confidence: 'high',
    },
    {
      id: 'dw-task-patient-intake',
      label: 'Patient Intake',
      description: 'Collect medical history, allergies, medications, and demographic information',
      parentTaskId: 'schedule-appointments',
      intentCategories: ['form-collection', 'data-entry', 'history-recording'],
      confidence: 'high',
    },
    {
      id: 'dw-task-treatment-cost-estimation',
      label: 'Treatment Cost Estimation',
      description: 'Calculate estimated costs for proposed treatments using treatment codes and insurance co-pays',
      parentTaskId: 'check-insurance',
      intentCategories: ['cost-calculation', 'financial-projection', 'insurance-deduction'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-emergency-routing',
      label: 'Emergency Routing',
      description: 'Identify dental emergencies and route to emergency dentist or hospital',
      parentTaskId: 'answer-patient-questions',
      intentCategories: ['emergency-detection', 'escalation', 'referral-coordination'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-followup-management',
      label: 'Follow-Up Management',
      description: 'Track post-treatment recovery, schedule follow-ups, and monitor complications',
      parentTaskId: 'schedule-appointments',
      intentCategories: ['patient-monitoring', 'care-continuity', 'outcome-tracking'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-coverage-lookup',
      label: 'Coverage Lookup',
      description: 'Search insurance plans for specific treatment code coverage levels and maximum benefits',
      parentTaskId: 'check-insurance',
      intentCategories: ['plan-search', 'benefit-discovery', 'coverage-comparison'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-patient-faq',
      label: 'Patient FAQ Response',
      description: 'Answer common patient questions about procedures, costs, and aftercare',
      parentTaskId: 'answer-patient-questions',
      intentCategories: ['qa-response', 'patient-education', 'information-delivery'],
      confidence: 'low',
    },
    {
      id: 'dw-task-consent-collection',
      label: 'Consent Collection',
      description: 'Obtain informed consent forms and verify patient understanding of treatment risks',
      parentTaskId: 'schedule-appointments',
      intentCategories: ['consent-documentation', 'risk-disclosure', 'legal-compliance'],
      confidence: 'low',
    },
  ],
  dataDimensions: [
    {
      id: 'dw-data-patient-records',
      label: 'Patient Records Database',
      depthScore: 5,
      subTopics: [
        { name: 'Clinical history', depth: 5 },
        { name: 'Appointment history', depth: 5 },
        { name: 'Treatment records', depth: 4 },
        { name: 'Allergies and medications', depth: 4 },
      ],
      keyEntities: ['patient-id', 'medical-history', 'treatment-date', 'provider-notes', 'imaging-results'],
      connectedDomains: ['clinical-data', 'patient-safety', 'care-continuity', 'compliance-hipaa'],
      sourceAttribution: [
        { sourceId: 'patient-records', sourceName: 'patient_records.db', count: '8420' },
      ],
      gapNote: 'Missing real-time integration with lab and imaging systems for complete clinical picture',
    },
    {
      id: 'dw-data-insurance-plans',
      label: 'Insurance Plans Reference',
      depthScore: 4,
      subTopics: [
        { name: 'Plan types and tiers', depth: 4 },
        { name: 'Coverage percentages', depth: 4 },
        { name: 'Deductibles and maximums', depth: 3 },
        { name: 'Excluded procedures', depth: 3 },
      ],
      keyEntities: ['plan-code', 'carrier-name', 'coverage-percent', 'annual-maximum', 'waiting-period'],
      connectedDomains: ['insurance-management', 'benefits-administration', 'financial-planning'],
      sourceAttribution: [
        { sourceId: 'insurance-plans', sourceName: 'insurance_plans.pdf', count: '156' },
      ],
      gapNote: 'Plan documents updated quarterly but real-time carrier eligibility verification unavailable',
    },
    {
      id: 'dw-data-treatment-codes',
      label: 'Treatment Codes & Pricing',
      depthScore: 4,
      subTopics: [
        { name: 'ADA procedure codes', depth: 4 },
        { name: 'Base fee schedules', depth: 4 },
        { name: 'Insurance fee adjustments', depth: 3 },
        { name: 'Recommended follow-up intervals', depth: 2 },
      ],
      keyEntities: ['ada-code', 'procedure-name', 'base-fee', 'time-estimate', 'equipment-required'],
      connectedDomains: ['clinical-procedures', 'fee-management', 'treatment-planning'],
      sourceAttribution: [
        { sourceId: 'treatment-codes', sourceName: 'treatment_codes.csv', count: '342' },
      ],
    },
  ],
  userProfileDimensions: [
    {
      id: 'dw-up-patient',
      label: 'Patient',
      description: 'End patient seeking dental care, scheduling, and cost transparency',
      contextAxis: 'health-seeking',
      postureAxis: 'convenience-focused',
      channelAxis: 'web-mobile-voice',
      behaviorImpact: 'Expects fast scheduling, upfront cost estimates, and simple appointment confirmations',
    },
    {
      id: 'dw-up-office-staff',
      label: 'Office Staff',
      description: 'Front desk and administrative staff managing appointments and patient intake',
      contextAxis: 'operational-management',
      postureAxis: 'efficiency-seeking',
      channelAxis: 'practice-management-system',
      behaviorImpact: 'Requires quick insurance verification and automated intake to reduce manual data entry',
    },
    {
      id: 'dw-up-system-user',
      label: 'System Administrator',
      description: 'IT staff maintaining systems and ensuring data integrity',
      contextAxis: 'system-governance',
      postureAxis: 'reliability-focused',
      channelAxis: 'api-integration',
      behaviorImpact: 'Demands high uptime, audit logs, and HIPAA-compliant data handling',
    },
    {
      id: 'dw-up-insurance-coordinator',
      label: 'Insurance Coordinator',
      description: 'Staff verifying patient coverage and managing insurance claims',
      contextAxis: 'insurance-management',
      postureAxis: 'accuracy-driven',
      channelAxis: 'insurance-portal',
      behaviorImpact: 'Needs real-time eligibility checks and automated benefits estimation to prevent claim denials',
    },
    {
      id: 'dw-up-dentist',
      label: 'Dentist',
      description: 'Clinical provider making treatment decisions and reviewing patient data',
      contextAxis: 'clinical-delivery',
      postureAxis: 'patient-safety-focused',
      channelAxis: 'clinical-workstation',
      behaviorImpact: 'Requires quick access to medical history, imaging, and treatment recommendations',
    },
    {
      id: 'dw-up-clinical-staff',
      label: 'Clinical Staff',
      description: 'Hygienists and dental assistants supporting chair-side care',
      contextAxis: 'clinical-support',
      postureAxis: 'workflow-optimization',
      channelAxis: 'clinical-tablet',
      behaviorImpact: 'Expects real-time alerts for allergies and quick patient intake summaries',
    },
  ],
  summaryText: 'The Decision Workflow Agent streamlines dental practice operations by orchestrating appointment scheduling, insurance verification, clinical triage, and cost estimation across patient records, insurance plans, and treatment code databases. It empowers office staff, dentists, and patients with automated workflows that reduce administrative burden while ensuring clinical safety and financial transparency.',
}

export const CODING_AGENT_DIMENSIONS: DimensionAnalysisPayload = {
  tileId: 'coding-agent',
  agentName: 'Coding Agent',
  taskDimensions: [
    {
      id: 'ca-task-feature-implementation',
      label: 'Feature Implementation',
      description: 'Design and code new features following architecture and coding standards',
      parentTaskId: 'implement-feature',
      intentCategories: ['code-generation', 'design-patterns', 'integration-logic'],
      confidence: 'high',
    },
    {
      id: 'ca-task-bug-diagnosis',
      label: 'Bug Diagnosis',
      description: 'Identify root causes of bugs through code analysis and log examination',
      parentTaskId: 'debug-issue',
      intentCategories: ['error-analysis', 'stack-trace-parsing', 'reproduction-strategy'],
      confidence: 'high',
    },
    {
      id: 'ca-task-test-generation',
      label: 'Test Generation',
      description: 'Create unit and integration tests with appropriate coverage and edge cases',
      parentTaskId: 'write-tests',
      intentCategories: ['test-design', 'mock-creation', 'coverage-analysis'],
      confidence: 'high',
    },
    {
      id: 'ca-task-code-refactoring',
      label: 'Code Refactoring',
      description: 'Improve code quality, reduce technical debt, and optimize performance',
      parentTaskId: 'implement-feature',
      intentCategories: ['clean-code', 'duplication-removal', 'optimization'],
      confidence: 'high',
    },
    {
      id: 'ca-task-api-design',
      label: 'API Design',
      description: 'Design RESTful or GraphQL APIs with proper versioning and documentation',
      parentTaskId: 'implement-feature',
      intentCategories: ['api-spec', 'endpoint-design', 'schema-validation'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-documentation-generation',
      label: 'Documentation Generation',
      description: 'Create or update API documentation, architecture diagrams, and code comments',
      parentTaskId: 'implement-feature',
      intentCategories: ['doc-generation', 'inline-comments', 'api-examples'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-dependency-analysis',
      label: 'Dependency Analysis',
      description: 'Audit library versions, identify security vulnerabilities, and plan upgrades',
      parentTaskId: 'debug-issue',
      intentCategories: ['vulnerability-scan', 'version-conflict', 'compatibility-check'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-performance-optimization',
      label: 'Performance Optimization',
      description: 'Profile code, identify bottlenecks, and implement caching or algorithmic improvements',
      parentTaskId: 'debug-issue',
      intentCategories: ['profiling', 'bottleneck-detection', 'algorithm-optimization'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-security-review',
      label: 'Security Review',
      description: 'Identify vulnerabilities, injection risks, authentication gaps, and data exposure',
      parentTaskId: 'implement-feature',
      intentCategories: ['vulnerability-detection', 'owasp-compliance', 'encryption-review'],
      confidence: 'low',
    },
    {
      id: 'ca-task-architecture-assessment',
      label: 'Architecture Assessment',
      description: 'Evaluate system design, scalability limits, and propose architectural improvements',
      parentTaskId: 'implement-feature',
      intentCategories: ['system-design', 'scalability-analysis', 'pattern-matching'],
      confidence: 'low',
    },
  ],
  dataDimensions: [
    {
      id: 'ca-data-codebase-repo',
      label: 'Codebase Repository',
      depthScore: 5,
      subTopics: [
        { name: 'Source code structure', depth: 5 },
        { name: 'Git commit history', depth: 4 },
        { name: 'Branch strategy', depth: 4 },
        { name: 'Configuration files', depth: 3 },
      ],
      keyEntities: ['package.json', 'tsconfig.json', 'src-directory', 'dockerfile', 'env-config'],
      connectedDomains: ['source-control', 'build-pipeline', 'dependency-management', 'deployment'],
      sourceAttribution: [
        { sourceId: 'codebase-repo', sourceName: 'repository_snapshot.tar.gz', count: '2847' },
      ],
      gapNote: 'Historical performance benchmarks not included in snapshot; requires separate monitoring system',
    },
    {
      id: 'ca-data-api-docs',
      label: 'API Documentation',
      depthScore: 4,
      subTopics: [
        { name: 'Endpoint specifications', depth: 4 },
        { name: 'Request/response schemas', depth: 4 },
        { name: 'Authentication methods', depth: 3 },
        { name: 'Error codes and handling', depth: 3 },
      ],
      keyEntities: ['rest-endpoints', 'graphql-schema', 'oauth-flow', 'rate-limits', 'versioning-strategy'],
      connectedDomains: ['api-contract', 'client-integration', 'third-party-consumption'],
      sourceAttribution: [
        { sourceId: 'api-docs', sourceName: 'api_documentation.md', count: '156' },
      ],
      gapNote: 'OpenAPI spec format missing; documentation uses markdown format incompatible with code generators',
    },
    {
      id: 'ca-data-test-patterns',
      label: 'Test Suite Database',
      depthScore: 4,
      subTopics: [
        { name: 'Unit test coverage', depth: 4 },
        { name: 'Integration test scenarios', depth: 4 },
        { name: 'Mock data fixtures', depth: 3 },
        { name: 'Test execution results', depth: 2 },
      ],
      keyEntities: ['jest-config', 'test-fixtures', 'mock-services', 'e2e-scenarios', 'coverage-report'],
      connectedDomains: ['quality-assurance', 'ci-cd-pipeline', 'regression-prevention'],
      sourceAttribution: [
        { sourceId: 'test-patterns', sourceName: 'test_suite.db', count: '1247' },
      ],
      gapNote: 'Missing load testing scenarios and chaos engineering test cases',
    },
    {
      id: 'ca-data-style-guide',
      label: 'Code Style Guide',
      depthScore: 3,
      subTopics: [
        { name: 'Naming conventions', depth: 3 },
        { name: 'Formatting rules', depth: 3 },
        { name: 'Design patterns', depth: 2 },
        { name: 'Common pitfalls', depth: 2 },
      ],
      keyEntities: ['eslint-config', 'prettier-rules', 'component-architecture', 'file-structure', 'comments-style'],
      connectedDomains: ['code-quality', 'team-standards', 'maintainability'],
      sourceAttribution: [
        { sourceId: 'style-guide', sourceName: 'code_style_guide.md', count: '89' },
      ],
    },
  ],
  userProfileDimensions: [
    {
      id: 'ca-up-software-engineer',
      label: 'Software Engineer',
      description: 'Full-stack developer implementing features and maintaining codebase',
      contextAxis: 'feature-development',
      postureAxis: 'quality-focused',
      channelAxis: 'ide-cli',
      behaviorImpact: 'Expects smart code generation, automated testing, and instant architecture feedback',
    },
    {
      id: 'ca-up-junior-developer',
      label: 'Junior Developer',
      description: 'Early-career engineer learning patterns and expanding skillset',
      contextAxis: 'skill-building',
      postureAxis: 'learning-oriented',
      channelAxis: 'ide-documentation',
      behaviorImpact: 'Needs detailed code explanations, common pitfall warnings, and pattern references',
    },
    {
      id: 'ca-up-code-reviewer',
      label: 'Code Reviewer',
      description: 'Senior engineer reviewing PRs for quality, security, and design',
      contextAxis: 'quality-gate',
      postureAxis: 'standards-enforcement',
      channelAxis: 'pull-request-tool',
      behaviorImpact: 'Requires automated security checks, test coverage analysis, and architectural impact summaries',
    },
    {
      id: 'ca-up-devops-engineer',
      label: 'DevOps Engineer',
      description: 'Infrastructure and deployment specialist managing CI/CD and environments',
      contextAxis: 'infrastructure-as-code',
      postureAxis: 'reliability-driven',
      channelAxis: 'build-pipeline',
      behaviorImpact: 'Demands dependency scanning, container analysis, and deployment configuration validation',
    },
    {
      id: 'ca-up-qa-engineer',
      label: 'QA Engineer',
      description: 'Test automation and quality assurance professional',
      contextAxis: 'quality-validation',
      postureAxis: 'coverage-obsessed',
      channelAxis: 'testing-framework',
      behaviorImpact: 'Expects test coverage metrics, edge case identification, and automated regression detection',
    },
    {
      id: 'ca-up-architect',
      label: 'Solution Architect',
      description: 'Technical lead making strategic design and scalability decisions',
      contextAxis: 'system-design',
      postureAxis: 'strategic-planning',
      channelAxis: 'architecture-review',
      behaviorImpact: 'Needs scalability analysis, technical debt assessment, and long-term maintenance impact reports',
    },
  ],
  summaryText: 'The Coding Agent accelerates software development by analyzing repositories, APIs, tests, and style guides to automate feature implementation, bug diagnosis, refactoring, and security reviews. It serves engineers at all levels with context-aware code generation, architectural guidance, and automated quality checks integrated into IDE and CI/CD workflows.',
}
