import type {
  DimensionAnalysisPayload,
  OutputDimension,
  ToolDimension,
  ToolState,
} from '@/store/agentTypes'

export const DOC_INTELLIGENCE_DIMENSIONS: DimensionAnalysisPayload = {
  tileId: 'doc-intelligence',
  agentName: 'Loan Underwriting Agent',
  taskDimensions: [
    {
      id: 'doci-task-application-intake',
      label: 'Application Intake',
      description: 'Receive and validate loan application completeness',
      parentTaskId: 'eligibility-screening',
      intentCategories: ['intake', 'completeness-check', 'document-collection'],
      confidence: 'high',
    },
    {
      id: 'doci-task-credit-analysis',
      label: 'Credit Analysis',
      description: 'Extract and analyze credit score, payment history, and credit profile',
      parentTaskId: 'risk-scoring',
      intentCategories: ['credit-evaluation', 'score-extraction', 'history-analysis'],
      confidence: 'high',
    },
    {
      id: 'doci-task-income-verification',
      label: 'Income Verification',
      description: 'Cross-reference W-2, paystubs, tax returns, and bank statements for income validation',
      parentTaskId: 'document-verification',
      intentCategories: ['income-extraction', 'document-cross-reference', 'employment-verification'],
      confidence: 'high',
    },
    {
      id: 'doci-task-property-valuation',
      label: 'Property Valuation',
      description: 'Extract property value from appraisal and calculate LTV ratio',
      parentTaskId: 'risk-scoring',
      intentCategories: ['appraisal-analysis', 'ltv-calculation', 'collateral-assessment'],
      confidence: 'high',
    },
    {
      id: 'doci-task-dti-calculation',
      label: 'DTI Calculation',
      description: 'Calculate debt-to-income ratio from verified income and documented liabilities',
      parentTaskId: 'eligibility-screening',
      intentCategories: ['ratio-calculation', 'debt-analysis', 'financial-assessment'],
      confidence: 'high',
    },
    {
      id: 'doci-task-eligibility-check',
      label: 'Eligibility Check',
      description: 'Verify applicant meets loan program guidelines and underwriting criteria',
      parentTaskId: 'eligibility-screening',
      intentCategories: ['guideline-verification', 'policy-compliance', 'qualification-check'],
      confidence: 'high',
    },
    {
      id: 'doci-task-compliance-validation',
      label: 'Compliance Validation',
      description: 'Verify application meets regulatory requirements (Regulation B, ECOA, HMDA, TILA)',
      parentTaskId: 'risk-scoring',
      intentCategories: ['regulatory-check', 'fair-lending-validation', 'policy-enforcement'],
      confidence: 'high',
    },
    {
      id: 'doci-task-conditions-generation',
      label: 'Conditions Generation',
      description: 'Generate conditional approval requirements based on underwriting findings',
      parentTaskId: 'eligibility-screening',
      intentCategories: ['decision-output', 'condition-specification', 'approval-structuring'],
      confidence: 'medium',
    },
    {
      id: 'doci-task-decision-routing',
      label: 'Decision Routing',
      description: 'Route application for final decision (approval, conditional, denial, manual underwriting)',
      parentTaskId: 'risk-scoring',
      intentCategories: ['workflow-routing', 'decision-dispatch', 'escalation-handling'],
      confidence: 'high',
    },
    {
      id: 'doci-task-portfolio-assessment',
      label: 'Portfolio Assessment',
      description: 'Aggregate loan decisions and analyze portfolio-level risk metrics',
      parentTaskId: 'risk-scoring',
      intentCategories: ['aggregation', 'portfolio-analysis', 'trend-detection'],
      confidence: 'medium',
    },
  ],
  dataDimensions: [
    {
      id: 'doci-data-loan-apps',
      label: 'Loan Application Data',
      depthScore: 4,
      subTopics: [
        { name: 'Applicant demographics', depth: 4 },
        { name: 'Loan terms requested', depth: 4 },
        { name: 'Co-applicant information', depth: 3 },
        { name: 'Property details', depth: 3 },
      ],
      keyEntities: ['loan-amount', 'loan-type', 'property-address', 'borrower-name', 'co-borrower'],
      connectedDomains: ['mortgage-lending', 'application-intake', 'underwriting'],
      sourceAttribution: [
        { sourceId: 'loan-application-pdf', sourceName: 'Loan_Application_Form.pdf', count: '47' },
      ],
      gapNote: 'Co-borrower income sometimes incomplete; requires verification doc cross-reference',
    },
    {
      id: 'doci-data-credit-bureau',
      label: 'Credit Bureau Data',
      depthScore: 4,
      subTopics: [
        { name: 'Credit score', depth: 4 },
        { name: 'Payment history', depth: 4 },
        { name: 'Outstanding debt', depth: 3 },
        { name: 'Derogatory marks', depth: 3 },
      ],
      keyEntities: ['credit-score', 'payment-history', 'outstanding-debt', 'credit-utilization', 'derogatory-marks'],
      connectedDomains: ['credit-analysis', 'risk-assessment', 'fair-lending'],
      sourceAttribution: [
        { sourceId: 'credit-report-pdf', sourceName: 'Credit_Report_Experian.pdf', count: '52' },
      ],
      gapNote: 'Credit reports can be 30 days old; escalate if recent delinquencies suspected',
    },
    {
      id: 'doci-data-income-docs',
      label: 'Income & Employment Data',
      depthScore: 4,
      subTopics: [
        { name: 'W-2 income', depth: 4 },
        { name: 'Current paystubs', depth: 4 },
        { name: 'Employment verification', depth: 3 },
        { name: 'YTD earnings', depth: 3 },
      ],
      keyEntities: ['annual-income', 'employer-name', 'employment-length', 'w2-amount', 'ytd-earnings'],
      connectedDomains: ['income-verification', 'employment-validation', 'dti-calculation'],
      sourceAttribution: [
        { sourceId: 'income-verification-pdf', sourceName: 'W2_Income_Verification.pdf', count: '61' },
      ],
      gapNote: 'Self-employed income requires 2-year tax return review; commission income highly variable',
    },
    {
      id: 'doci-data-property-appraisals',
      label: 'Property Appraisal Data',
      depthScore: 4,
      subTopics: [
        { name: 'Appraised value', depth: 4 },
        { name: 'Property condition rating', depth: 3 },
        { name: 'Comparable sales', depth: 3 },
        { name: 'Flood zone designation', depth: 2 },
      ],
      keyEntities: ['appraised-value', 'property-type', 'comparable-sales', 'condition-rating', 'flood-zone'],
      connectedDomains: ['property-valuation', 'collateral-assessment', 'ltv-calculation'],
      sourceAttribution: [
        { sourceId: 'property-appraisal-pdf', sourceName: 'Property_Appraisal_Report.pdf', count: '15' },
      ],
      gapNote: 'Appraisals valid only 120 days; recapture if property materially altered post-appraisal',
    },
  ],
  userProfileDimensions: [
    {
      id: 'doci-up-system-user',
      label: 'System User',
      description: 'API-first automation for batch loan application processing',
      contextAxis: 'programmatic-integration',
      postureAxis: 'efficiency-focused',
      channelAxis: 'api-webhook',
      behaviorImpact: 'Requires high-accuracy extraction with audit trail for regulatory compliance',
    },
    {
      id: 'doci-up-business-user',
      label: 'Loan Officer',
      description: 'Mortgage loan officer reviewing applications and managing underwriting workflow',
      contextAxis: 'approval-authority',
      postureAxis: 'risk-averse',
      channelAxis: 'web-dashboard',
      behaviorImpact: 'Demands fair lending compliance checks and clear adverse-action notices',
    },
    {
      id: 'doci-up-end-user',
      label: 'Borrower',
      description: 'Loan applicant checking application status and submitting documents',
      contextAxis: 'applicant-engagement',
      postureAxis: 'outcome-focused',
      channelAxis: 'email-notification',
      behaviorImpact: 'Expects transparent status updates and clear document requirements',
    },
    {
      id: 'doci-up-auditor',
      label: 'Compliance Auditor',
      description: 'Internal or regulatory auditor verifying fair lending and regulatory compliance',
      contextAxis: 'regulatory-compliance',
      postureAxis: 'verification-focused',
      channelAxis: 'audit-trail-export',
      behaviorImpact: 'Requires complete decision rationale, HMDA audit trail, and fair lending evidence',
    },
    {
      id: 'doci-up-analyst',
      label: 'Risk Analyst',
      description: 'Portfolio risk analyst modeling default probability and loss severity',
      contextAxis: 'portfolio-risk',
      postureAxis: 'analytical-precision',
      channelAxis: 'data-export',
      behaviorImpact: 'Needs granular loan-level data, risk scores, and predictive model inputs',
    },
    {
      id: 'doci-up-procurement',
      label: 'Underwriter',
      description: 'Professional underwriter making final loan approval/denial decisions',
      contextAxis: 'decision-authority',
      postureAxis: 'approval-focused',
      channelAxis: 'application-queue',
      behaviorImpact: 'Seeks conditional-approval checklists, manual-underwriting flags, and adverse-action templates',
    },
  ],
  outputDimensions: [
    { id: 'doci-od-1', label: 'Eligibility — Success + Direct + One-shot', description: 'Application meets guideline; auto-approved', agentOutputId: 'doci-out-eligibility', agentOutputLabel: 'Eligibility Decision', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'doci-od-2', label: 'Eligibility — Success + Cross-referenced + One-shot', description: 'Multi-document income validation confirms DTI meets guidelines', agentOutputId: 'doci-out-eligibility', agentOutputLabel: 'Eligibility Decision', outcome: 'success', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'doci-od-3', label: 'Eligibility — Conditional + Direct + Conversational', description: 'Approval conditional on documentation; requires borrower follow-up', agentOutputId: 'doci-out-conditions', agentOutputLabel: 'Conditions List', outcome: 'partial', complexity: 'direct', interaction: 'conversational' },
    { id: 'doci-od-4', label: 'Risk Scoring — Success + Direct + One-shot', description: 'Credit score extracted and DTI calculated with confidence', agentOutputId: 'doci-out-risk-score', agentOutputLabel: 'Risk Assessment', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'doci-od-5', label: 'Risk Scoring — Success + Cross-referenced + One-shot', description: 'Multi-factor risk model integrates credit, income, property, and compliance signals', agentOutputId: 'doci-out-risk-score', agentOutputLabel: 'Risk Assessment', outcome: 'success', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'doci-od-6', label: 'Compliance — Success + Direct + One-shot', description: 'Fair lending validation passes; no adverse-action flags', agentOutputId: 'doci-out-eligibility', agentOutputLabel: 'Eligibility Decision', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'doci-od-7', label: 'Denial — Escalation + Cross-referenced + One-shot', description: 'Adverse-action notice generated; specific denial reasons documented', agentOutputId: 'doci-out-adverse-action', agentOutputLabel: 'Adverse Action Notice', outcome: 'escalation', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'doci-od-8', label: 'Manual Underwriting — Escalation + Inferred + Conversational', description: 'Complex profile (self-employed, unusual credit) routes to underwriter for manual review', agentOutputId: 'doci-out-underwriting-summary', agentOutputLabel: 'Underwriting Summary', outcome: 'escalation', complexity: 'inferred', interaction: 'conversational' },
    { id: 'doci-od-9', label: 'Fair Lending Flag — Escalation + Cross-referenced + One-shot', description: 'Potential fair lending concern detected; escalates to compliance auditor', agentOutputId: 'doci-out-eligibility', agentOutputLabel: 'Eligibility Decision', outcome: 'escalation', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'doci-od-10', label: 'Document Gap — Escalation + Direct + Conversational', description: 'Missing critical document; requests borrower to resubmit with required items', agentOutputId: 'doci-out-document-checklist', agentOutputLabel: 'Document Checklist', outcome: 'escalation', complexity: 'direct', interaction: 'conversational' },
  ],
  toolDimensions: [
    { id: 'doci-tooldim-credit-api', toolId: 'credit-bureau-api', toolName: 'Credit Bureau API', states: [
      { id: 'doci-ts-ca-read-success', label: 'Credit Fetch Success', operation: 'read', outcome: 'success', description: 'Credit report successfully retrieved from bureau' },
      { id: 'doci-ts-ca-read-failure', label: 'Credit Fetch Failure', operation: 'read', outcome: 'failure', description: 'Unable to pull report — invalid SSN or applicant not found' },
      { id: 'doci-ts-ca-read-timeout', label: 'Credit API Timeout', operation: 'read', outcome: 'timeout', description: 'Credit bureau API exceeded time threshold' },
    ] },
    { id: 'doci-tooldim-income-validator', toolId: 'income-validator', toolName: 'Income Validator', states: [
      { id: 'doci-ts-iv-read-success', label: 'Income Validation Success', operation: 'read', outcome: 'success', description: 'Income cross-verified across W-2, paystubs, tax returns' },
      { id: 'doci-ts-iv-read-failure', label: 'Income Validation Failure', operation: 'read', outcome: 'failure', description: 'Inconsistent income across documents — requires manual review' },
    ] },
    { id: 'doci-tooldim-appraisal-analyzer', toolId: 'appraisal-analyzer', toolName: 'Appraisal Analyzer', states: [
      { id: 'doci-ts-aa-read-success', label: 'Appraisal Parse Success', operation: 'read', outcome: 'success', description: 'Property value and LTV calculated from appraisal' },
      { id: 'doci-ts-aa-read-failure', label: 'Appraisal Parse Failure', operation: 'read', outcome: 'failure', description: 'Unable to extract value or property details from appraisal' },
    ] },
    { id: 'doci-tooldim-compliance-engine', toolId: 'compliance-engine', toolName: 'Compliance Engine', states: [
      { id: 'doci-ts-ce-read-success', label: 'Compliance Validation Success', operation: 'read', outcome: 'success', description: 'Application passes all regulatory checks' },
      { id: 'doci-ts-ce-read-failure', label: 'Compliance Flag', operation: 'read', outcome: 'failure', description: 'Potential fair lending or regulatory concern detected' },
    ] },
  ],
  summaryText: 'The Loan Underwriting Agent processes loan applications to extract financial data, validate eligibility, calculate risk metrics, and route decisions with full fair lending and HMDA compliance. It serves loan officers, borrowers, underwriters, and compliance auditors with automated eligibility screening, DTI/LTV calculations, risk scoring, conditions generation, and adverse-action notice creation. 10 response dimensions across 6 core outputs. 4 tools with 10 state transitions.',
}

export const DECISION_WORKFLOW_DIMENSIONS: DimensionAnalysisPayload = {
  tileId: 'decision-workflow',
  agentName: 'Care Coordination Agent',
  taskDimensions: [
    {
      id: 'dw-task-appointment-scheduling',
      label: 'Appointment Scheduling',
      description: 'Check provider availability and schedule appointments across healthcare network based on patient preferences and clinical needs',
      parentTaskId: 'appointment-scheduling',
      intentCategories: ['availability-check', 'booking', 'calendar-management', 'cross-provider'],
      confidence: 'high',
    },
    {
      id: 'dw-task-insurance-verification',
      label: 'Insurance Verification',
      description: 'Validate patient insurance coverage, eligibility, prior authorization requirements before referral or procedure',
      parentTaskId: 'insurance-verification',
      intentCategories: ['coverage-check', 'eligibility-verification', 'prior-auth-check'],
      confidence: 'high',
    },
    {
      id: 'dw-task-clinical-triage',
      label: 'Emergency Triage',
      description: 'Assess patient symptoms and clinical severity to determine appropriate care level and urgency',
      parentTaskId: 'emergency-triage',
      intentCategories: ['severity-assessment', 'condition-classification', 'routing-logic'],
      confidence: 'high',
    },
    {
      id: 'dw-task-patient-intake',
      label: 'Patient Data Collection',
      description: 'Collect demographics, medical history, medications, allergies, and care history for care coordination',
      parentTaskId: 'appointment-scheduling',
      intentCategories: ['form-collection', 'data-entry', 'history-recording'],
      confidence: 'high',
    },
    {
      id: 'dw-task-treatment-cost-estimation',
      label: 'Procedure Cost Estimation',
      description: 'Calculate estimated procedure costs using diagnosis codes (ICD-10), procedure codes (CPT), and insurance coverage',
      parentTaskId: 'insurance-verification',
      intentCategories: ['cost-calculation', 'financial-projection', 'coverage-deduction'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-emergency-routing',
      label: 'Emergency Routing',
      description: 'Detect medical emergencies and route patients to ED or on-call physician with appropriate context',
      parentTaskId: 'emergency-triage',
      intentCategories: ['emergency-detection', 'escalation', 'physician-notification'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-followup-management',
      label: 'Follow-Up Management',
      description: 'Track post-visit recovery, schedule follow-ups across providers, and monitor care plan adherence',
      parentTaskId: 'follow-up-coordination',
      intentCategories: ['patient-monitoring', 'care-continuity', 'outcome-tracking'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-coverage-lookup',
      label: 'Coverage & Benefits Lookup',
      description: 'Search insurance plans for procedure code coverage, deductibles, and maximum benefits',
      parentTaskId: 'insurance-verification',
      intentCategories: ['plan-search', 'benefit-discovery', 'coverage-comparison'],
      confidence: 'medium',
    },
    {
      id: 'dw-task-patient-faq',
      label: 'Patient Care Information',
      description: 'Provide information about appointments, procedures, recovery, and care coordination process',
      parentTaskId: 'appointment-scheduling',
      intentCategories: ['qa-response', 'patient-education', 'process-explanation'],
      confidence: 'low',
    },
    {
      id: 'dw-task-consent-collection',
      label: 'Consent Verification',
      description: 'Verify informed consent for procedures and validate patient understanding of clinical risks',
      parentTaskId: 'referral-management',
      intentCategories: ['consent-documentation', 'risk-disclosure', 'legal-compliance'],
      confidence: 'low',
    },
  ],
  dataDimensions: [
    {
      id: 'dw-data-patient-records',
      label: 'Patient Health Records (EHR)',
      depthScore: 5,
      subTopics: [
        { name: 'Patient demographics', depth: 5 },
        { name: 'Medical & surgical history', depth: 5 },
        { name: 'Medications and dosages', depth: 4 },
        { name: 'Allergies and contraindications', depth: 4 },
        { name: 'Care plans and goals', depth: 4 },
      ],
      keyEntities: ['patient-id', 'diagnosis-code', 'medication-list', 'allergy-list', 'care-plan-id'],
      connectedDomains: ['clinical-data', 'patient-safety', 'care-continuity', 'compliance-hipaa'],
      sourceAttribution: [
        { sourceId: 'patient-ehr', sourceName: 'Patient_EHR_Export.hl7', count: '18,650' },
      ],
      gapNote: 'Real-time lab and imaging integration needed for complete clinical picture across settings',
    },
    {
      id: 'dw-data-provider-network',
      label: 'Provider Network Directory',
      depthScore: 4,
      subTopics: [
        { name: 'Provider credentials (NPI)', depth: 4 },
        { name: 'Specialties and subspecialties', depth: 4 },
        { name: 'Network participation status', depth: 4 },
        { name: 'Availability and office hours', depth: 3 },
        { name: 'Accepting new patients', depth: 3 },
      ],
      keyEntities: ['provider-npi', 'specialty', 'network-status', 'availability', 'accepting-new'],
      connectedDomains: ['provider-management', 'referral-routing', 'access-management'],
      sourceAttribution: [
        { sourceId: 'provider-network', sourceName: 'Provider_Network.api', count: '2,847' },
      ],
      gapNote: 'Specialty matching and sub-specialty filters needed for complex referral scenarios',
    },
    {
      id: 'dw-data-insurance-benefits',
      label: 'Insurance & Benefits Data',
      depthScore: 4,
      subTopics: [
        { name: 'Coverage types', depth: 4 },
        { name: 'Copay and deductible amounts', depth: 4 },
        { name: 'Prior authorization requirements', depth: 4 },
        { name: 'In-network status', depth: 3 },
        { name: 'Annual maximums', depth: 3 },
      ],
      keyEntities: ['insurance-id', 'coverage-type', 'copay-amount', 'deductible-remaining', 'prior-auth-required'],
      connectedDomains: ['insurance-management', 'benefits-verification', 'financial-planning'],
      sourceAttribution: [
        { sourceId: 'insurance-api', sourceName: 'Insurance_Eligibility.api', count: '4,192' },
      ],
      gapNote: 'Real-time carrier eligibility checks working; historical claim data integration pending',
    },
    {
      id: 'dw-data-clinical-guidelines',
      label: 'Clinical Guidelines & Protocols',
      depthScore: 4,
      subTopics: [
        { name: 'Clinical pathways by diagnosis', depth: 4 },
        { name: 'Evidence-based recommendations', depth: 4 },
        { name: 'Contraindication rules', depth: 4 },
        { name: 'Screening and prevention protocols', depth: 3 },
        { name: 'Dosing and medication guidelines', depth: 3 },
      ],
      keyEntities: ['clinical-pathway', 'evidence-grade', 'contraindication', 'dosing-guideline', 'screening-schedule'],
      connectedDomains: ['clinical-decision-support', 'quality-assurance', 'patient-safety'],
      sourceAttribution: [
        { sourceId: 'clinical-guidelines', sourceName: 'Clinical_Guidelines_v12.pdf', count: '247' },
      ],
      gapNote: 'Guidelines updated quarterly; specialty-specific pathways expanding coverage',
    },
  ],
  userProfileDimensions: [
    {
      id: 'dw-up-patient',
      label: 'Patient',
      description: 'Patient seeking appointments, referrals, and clear information about insurance and care plans',
      contextAxis: 'health-seeking',
      postureAxis: 'convenience-focused',
      channelAxis: 'web-mobile-voice-portal',
      behaviorImpact: 'Expects fast scheduling, transparent insurance costs, clear referral status, and automated appointment reminders',
    },
    {
      id: 'dw-up-care-coordinator',
      label: 'Care Coordinator',
      description: 'Staff managing cross-provider coordination, referrals, and insurance verification',
      contextAxis: 'care-management',
      postureAxis: 'efficiency-seeking',
      channelAxis: 'ehr-system',
      behaviorImpact: 'Requires fast insurance eligibility checks, automated referral routing, and cross-provider care synchronization',
    },
    {
      id: 'dw-up-system-user',
      label: 'System Administrator',
      description: 'IT staff maintaining EHR systems, APIs, and ensuring data integrity across providers',
      contextAxis: 'system-governance',
      postureAxis: 'reliability-focused',
      channelAxis: 'api-integration',
      behaviorImpact: 'Demands high uptime, HL7-FHIR interoperability, complete audit logs, and HIPAA-compliant data handling',
    },
    {
      id: 'dw-up-insurance-coordinator',
      label: 'Insurance Coordinator',
      description: 'Staff verifying coverage, managing prior authorizations, and resolving insurance issues',
      contextAxis: 'insurance-management',
      postureAxis: 'accuracy-driven',
      channelAxis: 'insurance-api-portal',
      behaviorImpact: 'Needs real-time eligibility verification and prior authorization status to prevent claim denials',
    },
    {
      id: 'dw-up-physician',
      label: 'Physician',
      description: 'Clinical provider making diagnostic and treatment decisions and approving referrals',
      contextAxis: 'clinical-delivery',
      postureAxis: 'patient-safety-focused',
      channelAxis: 'ehr-workstation',
      behaviorImpact: 'Requires rapid access to complete EHR, clinical history, labs, imaging, and referral recommendations',
    },
    {
      id: 'dw-up-nurse',
      label: 'Nurse',
      description: 'Clinical staff performing triage, patient monitoring, and follow-up coordination',
      contextAxis: 'clinical-support',
      postureAxis: 'workflow-optimization',
      channelAxis: 'ehr-mobile-phone',
      behaviorImpact: 'Expects real-time clinical alerts, allergy/medication warnings, and automated follow-up scheduling',
    },
    {
      id: 'dw-up-admin-staff',
      label: 'Administrative Staff',
      description: 'Staff handling scheduling, registration, and patient intake across provider locations',
      contextAxis: 'operations-management',
      postureAxis: 'process-efficiency',
      channelAxis: 'scheduling-system',
      behaviorImpact: 'Needs quick appointment availability, automated insurance collection, and confirmation workflows',
    },
  ],
  outputDimensions: [
    { id: 'dw-od-1', label: 'Appointment Confirmation — Success + Direct + One-shot', description: 'Appointment scheduled and confirmed with patient and providers', agentOutputId: 'cc-out-appointment-confirmation', agentOutputLabel: 'Appointment Confirmation', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'dw-od-2', label: 'Insurance Eligibility — Success + Direct + One-shot', description: 'Insurance coverage and prior authorization verified from carrier', agentOutputId: 'cc-out-insurance-eligibility', agentOutputLabel: 'Insurance Eligibility Result', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'dw-od-3', label: 'Insurance Eligibility — Partial + Direct + Conversational', description: 'Coverage partially verified — requires manual follow-up with carrier', agentOutputId: 'cc-out-insurance-eligibility', agentOutputLabel: 'Insurance Eligibility Result', outcome: 'partial', complexity: 'direct', interaction: 'conversational' },
    { id: 'dw-od-4', label: 'Referral Request — Success + Cross-referenced + One-shot', description: 'Referral initiated with provider matching and prior authorization', agentOutputId: 'cc-out-referral-request', agentOutputLabel: 'Referral Request', outcome: 'success', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'dw-od-5', label: 'Triage Assessment — Success + Direct + One-shot', description: 'Emergency severity assessed and routed to appropriate care level', agentOutputId: 'cc-out-triage-assessment', agentOutputLabel: 'Triage Assessment', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'dw-od-6', label: 'Triage Assessment — Escalation + Direct + One-shot', description: 'Emergency detected and escalated to on-call physician immediately', agentOutputId: 'cc-out-triage-assessment', agentOutputLabel: 'Triage Assessment', outcome: 'escalation', complexity: 'direct', interaction: 'one-shot' },
    { id: 'dw-od-7', label: 'Care Plan Summary — Success + Cross-referenced + One-shot', description: 'Post-visit care instructions synthesizing clinical notes and guidelines', agentOutputId: 'cc-out-care-plan-summary', agentOutputLabel: 'Care Plan Summary', outcome: 'success', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'dw-od-8', label: 'Follow-up Reminder — Success + Direct + Conversational', description: 'Automated follow-up scheduled with patient confirmation', agentOutputId: 'cc-out-followup-reminder', agentOutputLabel: 'Follow-up Reminder', outcome: 'success', complexity: 'direct', interaction: 'conversational' },
    { id: 'dw-od-9', label: 'Escalation — Escalation + Direct + One-shot', description: 'Clinical decision or insurance dispute escalated to appropriate authority', agentOutputId: 'cc-out-triage-assessment', agentOutputLabel: 'Triage Assessment', outcome: 'escalation', complexity: 'direct', interaction: 'one-shot' },
  ],
  toolDimensions: [
    { id: 'dw-tooldim-ehr', toolId: 'ehr-connector', toolName: 'EHR Connector (HL7-FHIR)', states: [
      { id: 'dw-ts-ehr-read-success', label: 'EHR Fetch Success', operation: 'read', outcome: 'success', description: 'Patient EHR data successfully retrieved with full history' },
      { id: 'dw-ts-ehr-read-failure', label: 'EHR Fetch Failure', operation: 'read', outcome: 'failure', description: 'Patient record not found or EHR unavailable' },
      { id: 'dw-ts-ehr-read-partial', label: 'EHR Partial Data', operation: 'read', outcome: 'partial', description: 'EHR retrieved but critical fields missing (allergies, medications)' },
    ] },
    { id: 'dw-tooldim-insurance', toolId: 'insurance-api', toolName: 'Insurance Verification API', states: [
      { id: 'dw-ts-ins-read-success', label: 'Eligibility Verified', operation: 'read', outcome: 'success', description: 'Insurance coverage and eligibility verified in real-time' },
      { id: 'dw-ts-ins-read-failure', label: 'Verification Failed', operation: 'read', outcome: 'failure', description: 'Insurance plan not found or carrier timeout' },
      { id: 'dw-ts-ins-prior-auth', label: 'Prior Auth Required', operation: 'read', outcome: 'conditional', description: 'Coverage confirmed but prior authorization required' },
    ] },
    { id: 'dw-tooldim-scheduling', toolId: 'scheduling-engine', toolName: 'Scheduling Engine', states: [
      { id: 'dw-ts-sched-read-success', label: 'Availability Found', operation: 'read', outcome: 'success', description: 'Provider appointment slots successfully queried' },
      { id: 'dw-ts-sched-create-success', label: 'Appointment Booked', operation: 'create', outcome: 'success', description: 'Appointment successfully scheduled and confirmed' },
      { id: 'dw-ts-sched-no-availability', label: 'No Slots Available', operation: 'read', outcome: 'failure', description: 'No available appointment slots for requested timeframe' },
    ] },
    { id: 'dw-tooldim-referral', toolId: 'referral-router', toolName: 'Referral Router', states: [
      { id: 'dw-ts-ref-match-success', label: 'Provider Matched', operation: 'read', outcome: 'success', description: 'Appropriate specialist matched and referral prepared' },
      { id: 'dw-ts-ref-submit-success', label: 'Referral Submitted', operation: 'create', outcome: 'success', description: 'Referral successfully sent to receiving provider' },
      { id: 'dw-ts-ref-no-match', label: 'No Match Found', operation: 'read', outcome: 'failure', description: 'No in-network specialist matches referral criteria' },
    ] },
  ],
  summaryText: 'The Care Coordination Agent streamlines healthcare delivery by orchestrating appointment scheduling, referrals, insurance verification, emergency triage, and follow-up management across provider networks. It empowers care coordinators, patients, and providers with automated workflows that reduce administrative burden while ensuring clinical safety and care continuity. 9 response dimensions across 5 core outputs. 4 tools with 13 state transitions. HL7-FHIR interoperability across EHR systems.',
}

export const CODING_AGENT_DIMENSIONS: DimensionAnalysisPayload = {
  tileId: 'coding-agent',
  agentName: 'Coding Agent',
  taskDimensions: [
    {
      id: 'ca-task-feature-implementation',
      label: 'Alert Triage',
      description: 'Classify and prioritize incoming alerts by severity and incident scope',
      parentTaskId: 'triage-alert',
      intentCategories: ['alert-classification', 'severity-assessment', 'incident-routing'],
      confidence: 'high',
    },
    {
      id: 'ca-task-bug-diagnosis',
      label: 'Root Cause Analysis',
      description: 'Identify incident root causes through metrics analysis and log examination',
      parentTaskId: 'analyze-incident',
      intentCategories: ['error-analysis', 'trace-parsing', 'correlation-detection'],
      confidence: 'high',
    },
    {
      id: 'ca-task-test-generation',
      label: 'Remediation Validation',
      description: 'Verify that remediation procedures resolve incidents without side effects',
      parentTaskId: 'validate-fix',
      intentCategories: ['health-check', 'smoke-test', 'regression-analysis'],
      confidence: 'high',
    },
    {
      id: 'ca-task-code-refactoring',
      label: 'Service Recovery',
      description: 'Execute automated remediation, rollback procedures, and state restoration',
      parentTaskId: 'execute-recovery',
      intentCategories: ['service-restart', 'state-restoration', 'traffic-shifting'],
      confidence: 'high',
    },
    {
      id: 'ca-task-api-design',
      label: 'Blast Radius Assessment',
      description: 'Evaluate incident impact scope across dependent services and data stores',
      parentTaskId: 'assess-impact',
      intentCategories: ['dependency-mapping', 'impact-calculation', 'risk-scoring'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-documentation-generation',
      label: 'Documentation Generation',
      description: 'Create or update API documentation, architecture diagrams, and code comments',
      parentTaskId: 'implement-feature',
      intentCategories: ['doc-generation', 'inline-comments', 'api-examples'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-dependency-analysis',
      label: 'Dependency Analysis',
      description: 'Audit library versions, identify security vulnerabilities, and plan upgrades',
      parentTaskId: 'debug-issue',
      intentCategories: ['vulnerability-scan', 'version-conflict', 'compatibility-check'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-performance-optimization',
      label: 'Performance Optimization',
      description: 'Profile code, identify bottlenecks, and implement caching or algorithmic improvements',
      parentTaskId: 'debug-issue',
      intentCategories: ['profiling', 'bottleneck-detection', 'algorithm-optimization'],
      confidence: 'medium',
    },
    {
      id: 'ca-task-security-review',
      label: 'Security Review',
      description: 'Identify vulnerabilities, injection risks, authentication gaps, and data exposure',
      parentTaskId: 'implement-feature',
      intentCategories: ['vulnerability-detection', 'owasp-compliance', 'encryption-review'],
      confidence: 'low',
    },
    {
      id: 'ca-task-architecture-assessment',
      label: 'Postmortem Generation',
      description: 'Synthesize incident timeline, root cause, and remediation actions into structured postmortem documentation',
      parentTaskId: 'document-incident',
      intentCategories: ['timeline-assembly', 'learning-extraction', 'action-tracking'],
      confidence: 'low',
    },
  ],
  dataDimensions: [
    {
      id: 'ca-data-codebase-repo',
      label: 'Codebase Repository',
      depthScore: 5,
      subTopics: [
        { name: 'Source code structure', depth: 5 },
        { name: 'Git commit history', depth: 4 },
        { name: 'Branch strategy', depth: 4 },
        { name: 'Configuration files', depth: 3 },
      ],
      keyEntities: ['package.json', 'tsconfig.json', 'src-directory', 'dockerfile', 'env-config'],
      connectedDomains: ['source-control', 'build-pipeline', 'dependency-management', 'deployment'],
      sourceAttribution: [
        { sourceId: 'codebase-repo', sourceName: 'repository_snapshot.tar.gz', count: '2847' },
      ],
      gapNote: 'Historical performance benchmarks not included in snapshot; requires separate monitoring system',
    },
    {
      id: 'ca-data-api-docs',
      label: 'API Documentation',
      depthScore: 4,
      subTopics: [
        { name: 'Endpoint specifications', depth: 4 },
        { name: 'Request/response schemas', depth: 4 },
        { name: 'Authentication methods', depth: 3 },
        { name: 'Error codes and handling', depth: 3 },
      ],
      keyEntities: ['rest-endpoints', 'graphql-schema', 'oauth-flow', 'rate-limits', 'versioning-strategy'],
      connectedDomains: ['api-contract', 'client-integration', 'third-party-consumption'],
      sourceAttribution: [
        { sourceId: 'api-docs', sourceName: 'api_documentation.md', count: '156' },
      ],
      gapNote: 'OpenAPI spec format missing; documentation uses markdown format incompatible with code generators',
    },
    {
      id: 'ca-data-test-patterns',
      label: 'Test Suite Database',
      depthScore: 4,
      subTopics: [
        { name: 'Unit test coverage', depth: 4 },
        { name: 'Integration test scenarios', depth: 4 },
        { name: 'Mock data fixtures', depth: 3 },
        { name: 'Test execution results', depth: 2 },
      ],
      keyEntities: ['jest-config', 'test-fixtures', 'mock-services', 'e2e-scenarios', 'coverage-report'],
      connectedDomains: ['quality-assurance', 'ci-cd-pipeline', 'regression-prevention'],
      sourceAttribution: [
        { sourceId: 'test-patterns', sourceName: 'test_suite.db', count: '1247' },
      ],
      gapNote: 'Missing load testing scenarios and chaos engineering test cases',
    },
    {
      id: 'ca-data-style-guide',
      label: 'Code Style Guide',
      depthScore: 3,
      subTopics: [
        { name: 'Naming conventions', depth: 3 },
        { name: 'Formatting rules', depth: 3 },
        { name: 'Design patterns', depth: 2 },
        { name: 'Common pitfalls', depth: 2 },
      ],
      keyEntities: ['eslint-config', 'prettier-rules', 'component-architecture', 'file-structure', 'comments-style'],
      connectedDomains: ['code-quality', 'team-standards', 'maintainability'],
      sourceAttribution: [
        { sourceId: 'style-guide', sourceName: 'code_style_guide.md', count: '89' },
      ],
    },
  ],
  userProfileDimensions: [
    {
      id: 'ca-up-software-engineer',
      label: 'Software Engineer',
      description: 'Full-stack developer implementing features and maintaining codebase',
      contextAxis: 'feature-development',
      postureAxis: 'quality-focused',
      channelAxis: 'ide-cli',
      behaviorImpact: 'Expects smart code generation, automated testing, and instant architecture feedback',
    },
    {
      id: 'ca-up-junior-developer',
      label: 'Junior Developer',
      description: 'Early-career engineer learning patterns and expanding skillset',
      contextAxis: 'skill-building',
      postureAxis: 'learning-oriented',
      channelAxis: 'ide-documentation',
      behaviorImpact: 'Needs detailed code explanations, common pitfall warnings, and pattern references',
    },
    {
      id: 'ca-up-code-reviewer',
      label: 'Code Reviewer',
      description: 'Senior engineer reviewing PRs for quality, security, and design',
      contextAxis: 'quality-gate',
      postureAxis: 'standards-enforcement',
      channelAxis: 'pull-request-tool',
      behaviorImpact: 'Requires automated security checks, test coverage analysis, and architectural impact summaries',
    },
    {
      id: 'ca-up-devops-engineer',
      label: 'DevOps Engineer',
      description: 'Infrastructure and deployment specialist managing CI/CD and environments',
      contextAxis: 'infrastructure-as-code',
      postureAxis: 'reliability-driven',
      channelAxis: 'build-pipeline',
      behaviorImpact: 'Demands dependency scanning, container analysis, and deployment configuration validation',
    },
    {
      id: 'ca-up-qa-engineer',
      label: 'QA Engineer',
      description: 'Test automation and quality assurance professional',
      contextAxis: 'quality-validation',
      postureAxis: 'coverage-obsessed',
      channelAxis: 'testing-framework',
      behaviorImpact: 'Expects test coverage metrics, edge case identification, and automated regression detection',
    },
    {
      id: 'ca-up-architect',
      label: 'Solution Architect',
      description: 'Technical lead making strategic design and scalability decisions',
      contextAxis: 'system-design',
      postureAxis: 'strategic-planning',
      channelAxis: 'architecture-review',
      behaviorImpact: 'Needs scalability analysis, technical debt assessment, and long-term maintenance impact reports',
    },
  ],
  outputDimensions: [
    { id: 'ca-od-1', label: 'Code Generation — Success + Direct + One-shot', description: 'Standalone function or class generated from spec', agentOutputId: 'ca-out-generation', agentOutputLabel: 'Code Generation', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'ca-od-2', label: 'Code Generation — Success + Cross-referenced + One-shot', description: 'Multi-module feature integrated with existing codebase', agentOutputId: 'ca-out-generation', agentOutputLabel: 'Code Generation', outcome: 'success', complexity: 'cross-referenced', interaction: 'one-shot' },
    { id: 'ca-od-3', label: 'Code Generation — Success + Cross-referenced + Conversational', description: 'Iterative code refinement with feedback loop', agentOutputId: 'ca-out-generation', agentOutputLabel: 'Code Generation', outcome: 'success', complexity: 'cross-referenced', interaction: 'conversational' },
    { id: 'ca-od-4', label: 'Root Cause Analysis — Success + Direct + One-shot', description: 'Root cause identified in metrics or logs', agentOutputId: 'ca-out-diagnosis', agentOutputLabel: 'Root Cause Analysis', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'ca-od-5', label: 'Root Cause Analysis — Success + Cross-referenced + Conversational', description: 'Multi-system incident requiring metrics and trace analysis', agentOutputId: 'ca-out-diagnosis', agentOutputLabel: 'Root Cause Analysis', outcome: 'success', complexity: 'cross-referenced', interaction: 'conversational' },
    { id: 'ca-od-6', label: 'Security Review — Success + Direct + One-shot', description: 'Vulnerability scan completed with severity assessment', agentOutputId: 'ca-out-security', agentOutputLabel: 'Security Review', outcome: 'success', complexity: 'direct', interaction: 'one-shot' },
    { id: 'ca-od-7', label: 'Security Review — Success + Inferred + Conversational', description: 'Deep security analysis with remediation recommendations', agentOutputId: 'ca-out-security', agentOutputLabel: 'Security Review', outcome: 'success', complexity: 'inferred', interaction: 'conversational' },
    { id: 'ca-od-8', label: 'Refactoring — Success + Cross-referenced + Conversational', description: 'Code structure improved with guided refactoring steps', agentOutputId: 'ca-out-refactoring', agentOutputLabel: 'Refactoring', outcome: 'success', complexity: 'cross-referenced', interaction: 'conversational' },
    { id: 'ca-od-9', label: 'Escalation — Escalation + Cross-referenced + Conversational', description: 'Complex architectural decision requiring specialist review', agentOutputId: 'ca-out-escalation', agentOutputLabel: 'Escalation Handoff', outcome: 'escalation', complexity: 'cross-referenced', interaction: 'conversational' },
  ],
  toolDimensions: [
    { id: 'ca-tooldim-repo', toolId: 'repo-analyzer', toolName: 'Repository Analyzer', states: [
      { id: 'ca-ts-repo-read-success', label: 'Repo Analysis Success', operation: 'read', outcome: 'success', description: 'Codebase structure and dependencies analyzed' },
      { id: 'ca-ts-repo-read-failure', label: 'Repo Analysis Failure', operation: 'read', outcome: 'failure', description: 'Repository inaccessible or parsing error' },
      { id: 'ca-ts-repo-read-timeout', label: 'Analysis Timeout', operation: 'read', outcome: 'timeout', description: 'Large codebase analysis exceeded time threshold' },
    ] },
    { id: 'ca-tooldim-linter', toolId: 'code-linter', toolName: 'Code Linter & Style Checker', states: [
      { id: 'ca-ts-lint-read-success', label: 'Lint Check Success', operation: 'read', outcome: 'success', description: 'Code linting completed with violations identified' },
      { id: 'ca-ts-lint-read-failure', label: 'Lint Check Failure', operation: 'read', outcome: 'failure', description: 'Linter unavailable or configuration error' },
    ] },
    { id: 'ca-tooldim-tests', toolId: 'test-runner', toolName: 'Test Execution Engine', states: [
      { id: 'ca-ts-test-create-success', label: 'Remediation Validation Success', operation: 'create', outcome: 'success', description: 'Remediation validated and verified operational' },
      { id: 'ca-ts-test-read-success', label: 'Test Execution Success', operation: 'read', outcome: 'success', description: 'Test suite executed with results' },
      { id: 'ca-ts-test-read-failure', label: 'Test Execution Failure', operation: 'read', outcome: 'failure', description: 'Test failures detected in code' },
    ] },
    { id: 'ca-tooldim-security', toolId: 'sast-scanner', toolName: 'SAST Security Scanner', states: [
      { id: 'ca-ts-sast-read-success', label: 'Scan Success', operation: 'read', outcome: 'success', description: 'Security scan completed with vulnerabilities identified' },
      { id: 'ca-ts-sast-read-timeout', label: 'Scan Timeout', operation: 'read', outcome: 'timeout', description: 'Security scan exceeded time limit' },
    ] },
  ],
  summaryText: 'The Incident Response Automation Agent accelerates incident resolution by analyzing metrics, logs, and runbooks to automate alert triage, root cause analysis, service recovery, and blast radius assessment. It serves incident responders at all levels with intelligent remediation recommendations, automated rollback procedures, and postmortem generation integrated into on-call workflows and SLO tracking. 9 response dimensions across 4 core outputs. 4 tools with 12 state transitions.',
}
