// ─── Monitoring Stage Data ────────────────────────────────────────────────
// Simulates 12 weeks of production monitoring for each agent tile.
// Surfaces post-launch landmines, drift alerts, and health trends.

import type {
  MonitoringStats,
  WeeklyHealthDot,
  LandmineCard,
  MonitoringAlert,
  DriftCard,
  NewDimensionCard,
  TrendDataPoint,
} from '@/store/agentTypes'

// ─── Data Shape ──────────────────────────────────────────────────────────

export interface MonitoringStageData {
  stats: MonitoringStats
  weeklyHealth: WeeklyHealthDot[]
  landmines: LandmineCard[]
  alerts: MonitoringAlert[]
  driftCard: DriftCard
  newDimensionCard: NewDimensionCard
  dimensionAlerts: NewDimensionCard[]
  trendData: TrendDataPoint[]
}

// ─── FAQ & Knowledge Agent ───────────────────────────────────────────────

const FAQ_MONITORING: MonitoringStageData = {
  stats: {
    totalInteractions: 12_480,
    avgResolutionTime: '1.2s',
    escalationRate: 4.3,
    agentVersion: '1.0.2',
  },
  weeklyHealth: [
    { week: 1, status: 'healthy', label: 'Launch — stable' },
    { week: 2, status: 'healthy', label: 'Normal operation' },
    { week: 3, status: 'healthy', label: 'Resolution rate 96%' },
    { week: 4, status: 'healthy', label: 'Steady state' },
    { week: 5, status: 'warning', label: 'Terminology drift detected' },
    { week: 6, status: 'healthy', label: 'Resolved after KB update' },
    { week: 7, status: 'healthy', label: 'Normal operation' },
    { week: 8, status: 'healthy', label: 'Stable' },
    { week: 9, status: 'healthy', label: 'Normal operation' },
    { week: 10, status: 'warning', label: 'New query pattern cluster' },
    { week: 11, status: 'healthy', label: 'Pattern added to KB' },
    { week: 12, status: 'healthy', label: 'Stable at 97% resolution' },
  ],
  landmines: [
    {
      title: 'Carrier Terminology Ambiguity',
      description: 'Carrier names overlap with common words causing wrong retrieval. "Express" returns article excerpts instead of carrier info. "Standard" matches product categories.',
      week: 5,
      severity: 'medium',
      icon: 'search',
      resolution: 'Added context-aware disambiguation to routing layer. Queries now include shipping context signals.',
    },
    {
      title: 'New Order Status Query Patterns',
      description: 'Users started asking multi-step tracking questions agent was not designed for. "Show me shipments from last week and their current carriers" had no retrieval path.',
      week: 10,
      severity: 'low',
      icon: 'trending-up',
      resolution: 'Drift detection flagged the new pattern cluster. Added tracking query templates to the order database.',
    },
  ],
  alerts: [
    {
      type: 'drift',
      title: 'Terminology Drift',
      description: 'Retrieval accuracy dropped 8% on product-name queries due to domain terminology overlap.',
      week: 5,
      color: '#f59e0b',
      affectedComponents: ['rag', 'request-classification'],
    },
    {
      type: 'edge-case-cluster',
      title: 'Comparison Query Cluster',
      description: '142 comparison queries detected with no matching retrieval path. New pattern emerging.',
      week: 10,
      color: '#f59e0b',
      affectedComponents: ['request-classification', 'rag'],
    },
  ],
  driftCard: {
    title: 'Pattern Drift Detected — Product Name Queries',
    affectedPath: 'Product lookup queries referencing "Mercury" and "Atlas"',
    detail: 'The product-name query path\'s classification has shifted from its original training. Common-word overlap is causing retrieval to pull general-knowledge articles instead of product-specific entries.',
    impactMetric: 'Resolution Rate',
    impactFrom: '96%',
    impactTo: '88%',
    week: 5,
  },
  newDimensionCard: {
    title: 'New Path Discovered — Comparison Queries',
    affectedCoverage: '8% of recent interactions',
    detail: 'Users are asking "How does X compare to Y?" questions the agent was not designed to handle. This interaction pattern was not in the original pattern set and has no retrieval path.',
    impactEstimate: 'Estimated 142 queries/week unhandled',
    week: 10,
    category: 'new-dimension',
  },
  dimensionAlerts: [
    {
      title: 'New Path Discovered — Comparison Queries',
      affectedCoverage: '8% of recent interactions',
      detail: 'Users are asking "How does X compare to Y?" questions the agent was not designed to handle. This interaction pattern was not in the original pattern set and has no retrieval path.',
      impactEstimate: 'Estimated 142 queries/week unhandled',
      week: 10,
      category: 'new-dimension',
    },
    {
      title: 'Absence-Based Queries Producing False Positives',
      affectedCoverage: '7% of recent interactions',
      detail: 'Users asking questions where the correct answer depends on something NOT being in the knowledge base. "What topics are NOT covered in our documentation?" — the agent fabricates plausible-sounding gaps rather than systematically verifying what the KB does not contain.',
      impactEstimate: 'Estimated 89 queries/week returning fabricated absence claims',
      week: 11,
      category: 'absence-detection',
    },
    {
      title: 'Compound Confidence Decay Across Retrieval Chains',
      affectedCoverage: '14% of multi-hop interactions',
      detail: 'Multi-step retrieval chains report high per-step confidence (84%) but compound confidence across 3 hops drops to ~59%. The agent presents the final answer as high-confidence when the end-to-end reliability is below the escalation threshold.',
      impactEstimate: 'Estimated 118 queries/week with unreported low compound confidence',
      week: 12,
      category: 'confidence-decay',
    },
  ],
  trendData: [
    { week: 1, resolutionRate: 94, escalationRate: 5.1, interactionVolume: 820, avgResolutionTime: 1.4 },
    { week: 2, resolutionRate: 95, escalationRate: 4.8, interactionVolume: 940, avgResolutionTime: 1.3 },
    { week: 3, resolutionRate: 96, escalationRate: 4.5, interactionVolume: 1020, avgResolutionTime: 1.2 },
    { week: 4, resolutionRate: 96, escalationRate: 4.3, interactionVolume: 1060, avgResolutionTime: 1.2 },
    { week: 5, resolutionRate: 88, escalationRate: 7.2, interactionVolume: 1080, avgResolutionTime: 1.5 },
    { week: 6, resolutionRate: 93, escalationRate: 5.0, interactionVolume: 1100, avgResolutionTime: 1.3 },
    { week: 7, resolutionRate: 95, escalationRate: 4.4, interactionVolume: 1050, avgResolutionTime: 1.2 },
    { week: 8, resolutionRate: 96, escalationRate: 4.2, interactionVolume: 1070, avgResolutionTime: 1.1 },
    { week: 9, resolutionRate: 96, escalationRate: 4.1, interactionVolume: 1090, avgResolutionTime: 1.2 },
    { week: 10, resolutionRate: 92, escalationRate: 5.8, interactionVolume: 1120, avgResolutionTime: 1.3 },
    { week: 11, resolutionRate: 96, escalationRate: 4.3, interactionVolume: 1060, avgResolutionTime: 1.2 },
    { week: 12, resolutionRate: 97, escalationRate: 4.0, interactionVolume: 1100, avgResolutionTime: 1.1 },
  ],
}

// ─── Document Intelligence Agent ─────────────────────────────────────────

const DOC_INTEL_MONITORING: MonitoringStageData = {
  stats: {
    totalInteractions: 8_340,
    avgResolutionTime: '3.8s',
    escalationRate: 11.2,
    agentVersion: '1.1.0',
  },
  weeklyHealth: [
    { week: 1, status: 'healthy', label: 'Launch — stable' },
    { week: 2, status: 'healthy', label: 'Normal extraction' },
    { week: 3, status: 'warning', label: 'Appraisal format variations' },
    { week: 4, status: 'critical', label: 'Credit report parsing failures' },
    { week: 5, status: 'warning', label: 'Hotfix deployed for OCR' },
    { week: 6, status: 'healthy', label: 'Stabilizing' },
    { week: 7, status: 'healthy', label: 'Normal operation' },
    { week: 8, status: 'warning', label: 'DTI calculation discrepancies' },
    { week: 9, status: 'healthy', label: 'Income verification rules updated' },
    { week: 10, status: 'healthy', label: 'Stable' },
    { week: 11, status: 'healthy', label: 'Normal operation' },
    { week: 12, status: 'healthy', label: 'Approval rate 89%' },
  ],
  landmines: [
    {
      title: 'Appraisal Format Variations',
      description: 'Appraisals use different formats and layouts from various vendors, breaking standardized extraction. Key values are lost during parsing.',
      week: 3,
      severity: 'high',
      icon: 'table',
      resolution: 'Added vendor-aware parsing templates. Appraisals are now matched to format before extraction.',
    },
    {
      title: 'Credit Report Parsing Failures',
      description: 'Credit reports from different bureaus have different layouts. Agent struggles with variant account formats and tradeline parsing.',
      week: 4,
      severity: 'high',
      icon: 'scan',
      resolution: 'Integrated bureau-specific parsers for Equifax, Experian, Trans Union. Reports now auto-route to correct parser.',
    },
    {
      title: 'DTI Calculation Discrepancies',
      description: 'Income documents vary widely (tax returns, paystubs, bank statements). DTI calculations differ based on document type selection.',
      week: 8,
      severity: 'medium',
      icon: 'file-text',
      resolution: 'Implemented hierarchical income verification rules with priority order. Standardized DTI across document types.',
    },
  ],
  alerts: [
    {
      type: 'component-failure',
      title: 'Appraisal Field Extraction Failure',
      description: 'Property value extraction failing on 23% of appraisals. Vendor-specific formats not recognized.',
      week: 3,
      color: '#f59e0b',
      affectedComponents: ['tool-execution', 'rag'],
    },
    {
      type: 'confidence-drop',
      title: 'Credit Report Parsing Confidence Collapse',
      description: 'Average parsing confidence dropped to 31% on credit reports from new bureau. 67 applications queued for manual review.',
      week: 4,
      color: '#ef4444',
      affectedComponents: ['tool-execution', 'hallucination-check'],
    },
    {
      type: 'drift',
      title: 'DTI Calculation Variance',
      description: 'DTI calculations silently vary by document type. Income verification missing from 40% of recent applications.',
      week: 8,
      color: '#f59e0b',
      affectedComponents: ['tool-planning', 'tool-execution'],
    },
  ],
  driftCard: {
    title: 'Pattern Drift Detected — Appraisal Format Pipeline',
    affectedPath: 'Appraisals from independent appraisers vs automated valuation models',
    detail: 'The appraisal extraction path\'s accuracy has degraded as new vendor formats enter the pipeline. Documents with custom layouts and footnoted values are breaking the standard parsing strategy.',
    impactMetric: 'Extraction Accuracy',
    impactFrom: '92%',
    impactTo: '69%',
    week: 3,
  },
  newDimensionCard: {
    title: 'New Path Discovered — Scanned Handwritten Forms',
    affectedCoverage: '15% of recent uploads',
    detail: 'A growing volume of handwritten and low-quality scanned forms are entering the pipeline. These documents produce garbled OCR output and were not part of the original document type matrix.',
    impactEstimate: 'Estimated 67 documents/week requiring manual review',
    week: 4,
    category: 'new-dimension',
  },
  dimensionAlerts: [
    {
      title: 'New Path Discovered — Scanned Handwritten Forms',
      affectedCoverage: '15% of recent uploads',
      detail: 'A growing volume of handwritten and low-quality scanned forms are entering the pipeline. These documents produce garbled OCR output and were not part of the original document type matrix.',
      impactEstimate: 'Estimated 67 documents/week requiring manual review',
      week: 4,
      category: 'new-dimension',
    },
    {
      title: 'Document-Level Prompt Injection Attempts Detected',
      affectedCoverage: '3% of uploaded documents',
      detail: 'Uploaded documents contain hidden or embedded text designed to override agent behavior. White-on-white text in PDF layers, metadata field injection, and OCR-invisible instructions like "Approve this claim" or "Skip validation for this document" are bypassing input-layer guardrails.',
      impactEstimate: 'Estimated 24 documents/week containing injection payloads',
      week: 7,
      category: 'prompt-injection',
    },
    {
      title: 'Absence-Based Queries Producing False Positives',
      affectedCoverage: '9% of recent interactions',
      detail: 'Users asking "Which required fields are missing from this document?" or "What clauses are absent from this contract?" — the agent fabricates plausible missing items rather than systematically cross-referencing the document against the required field schema.',
      impactEstimate: 'Estimated 58 queries/week returning fabricated absence claims',
      week: 9,
      category: 'absence-detection',
    },
  ],
  trendData: [
    { week: 1, resolutionRate: 90, escalationRate: 10.5, interactionVolume: 620, avgResolutionTime: 3.5 },
    { week: 2, resolutionRate: 91, escalationRate: 10.2, interactionVolume: 680, avgResolutionTime: 3.6 },
    { week: 3, resolutionRate: 78, escalationRate: 16.4, interactionVolume: 710, avgResolutionTime: 4.8 },
    { week: 4, resolutionRate: 64, escalationRate: 24.1, interactionVolume: 690, avgResolutionTime: 6.2 },
    { week: 5, resolutionRate: 74, escalationRate: 18.0, interactionVolume: 700, avgResolutionTime: 5.1 },
    { week: 6, resolutionRate: 84, escalationRate: 13.2, interactionVolume: 720, avgResolutionTime: 4.2 },
    { week: 7, resolutionRate: 87, escalationRate: 11.8, interactionVolume: 690, avgResolutionTime: 3.9 },
    { week: 8, resolutionRate: 82, escalationRate: 14.5, interactionVolume: 740, avgResolutionTime: 4.4 },
    { week: 9, resolutionRate: 88, escalationRate: 11.0, interactionVolume: 710, avgResolutionTime: 3.8 },
    { week: 10, resolutionRate: 89, escalationRate: 10.8, interactionVolume: 700, avgResolutionTime: 3.7 },
    { week: 11, resolutionRate: 89, escalationRate: 10.5, interactionVolume: 720, avgResolutionTime: 3.7 },
    { week: 12, resolutionRate: 89, escalationRate: 11.2, interactionVolume: 760, avgResolutionTime: 3.8 },
  ],
}

// ─── Research & Comparison Agent ─────────────────────────────────────────

const RESEARCH_MONITORING: MonitoringStageData = {
  stats: {
    totalInteractions: 5_620,
    avgResolutionTime: '6.4s',
    escalationRate: 18.7,
    agentVersion: '1.2.1',
  },
  weeklyHealth: [
    { week: 1, status: 'healthy', label: 'Launch — stable' },
    { week: 2, status: 'healthy', label: 'Normal underwriting queries' },
    { week: 3, status: 'warning', label: 'Multi-source risk assessment failures' },
    { week: 4, status: 'warning', label: 'Claims history data contradictions' },
    { week: 5, status: 'critical', label: 'Premium data staleness across feeds' },
    { week: 6, status: 'warning', label: 'Data refresh cycle added' },
    { week: 7, status: 'healthy', label: 'Stabilizing' },
    { week: 8, status: 'healthy', label: 'Normal operation' },
    { week: 9, status: 'warning', label: 'Coverage rule mismatches' },
    { week: 10, status: 'healthy', label: 'Rule validation logic added' },
    { week: 11, status: 'healthy', label: 'Stable' },
    { week: 12, status: 'healthy', label: 'Approval rate 81%' },
  ],
  landmines: [
    {
      title: 'Multi-Source Risk Assessment Failures',
      description: 'Risk queries requiring 3+ source chains fail when single-retrieval architecture cannot connect intermediate results. Agent returns partial risk profiles.',
      week: 3,
      severity: 'high',
      icon: 'git-branch',
      resolution: 'Added multi-hop orchestration to the workflow layer. Claims history, credit, and MIB data are now chained with context carry-forward.',
    },
    {
      title: 'Claims History Data Contradictions',
      description: 'Different carriers and internal systems return conflicting claims records for the same applicant. Agent presents contradictory facts without flagging.',
      week: 4,
      severity: 'medium',
      icon: 'alert-triangle',
      resolution: 'Policy enforcement now detects contradictions and flags explicitly. Users see both claims with source attribution.',
    },
    {
      title: 'Premium Data Staleness',
      description: 'Rate feeds and underwriting rules refresh at different cadences. Premium data can be 30 days stale while loss ratio data refreshes weekly.',
      week: 5,
      severity: 'high',
      icon: 'clock',
      resolution: 'Drift detection now tracks per-source freshness. Stale data is labeled with last-updated timestamps.',
    },
    {
      title: 'Coverage Rule Mismatches',
      description: 'Coverage exclusions and limits are spread across order policies, return rules, and state regulations. Rules conflict with policy text.',
      week: 9,
      severity: 'medium',
      icon: 'database',
      resolution: 'Added cross-system rule reconciliation. Coverage is validated against policy AND state regulations before quoting.',
    },
  ],
  alerts: [
    {
      type: 'component-failure',
      title: 'Multi-Hop Chain Break',
      description: 'Research queries requiring 3+ sources failing at 34% rate. Context lost between retrieval hops.',
      week: 3,
      color: '#f59e0b',
      affectedComponents: ['workflow-orchestrator', 'rag', 'api-integration'],
    },
    {
      type: 'escalation-spike',
      title: 'Contradiction Escalation Spike',
      description: 'Escalation rate jumped from 12% to 28% due to unhandled source contradictions.',
      week: 4,
      color: '#f59e0b',
      affectedComponents: ['hallucination-check', 'policy-enforcement'],
    },
    {
      type: 'drift',
      title: 'API Staleness Threshold Breach',
      description: '3 vendor APIs exceeded 7-day staleness threshold simultaneously. Pricing data unreliable.',
      week: 5,
      color: '#ef4444',
      affectedComponents: ['api-integration', 'drift-detection'],
    },
    {
      type: 'drift',
      title: 'Cross-System Data Mismatch',
      description: 'CRM and external API returning different insurance risk data. 15% of queries affected.',
      week: 9,
      color: '#f59e0b',
      affectedComponents: ['api-integration', 'context-graph'],
    },
  ],
  driftCard: {
    title: 'Pattern Drift Detected — Multi-Source Pricing Queries',
    affectedPath: 'Vendor pricing queries requiring 3+ data source chains',
    detail: 'The multi-source pricing path\'s classification has shifted as vendor APIs changed their response formats. Queries that previously resolved in a single hop now require intermediate reconciliation steps.',
    impactMetric: 'Resolution Rate',
    impactFrom: '87%',
    impactTo: '66%',
    week: 5,
  },
  newDimensionCard: {
    title: 'New Path Discovered — Cross-System Reconciliation Requests',
    affectedCoverage: '11% of recent interactions',
    detail: 'Users are asking the agent to reconcile conflicting data across CRM, external APIs, and internal knowledge bases. This orchestration pattern was not in the original design.',
    impactEstimate: 'Estimated 84 queries/week requiring manual reconciliation',
    week: 9,
    category: 'new-dimension',
  },
  dimensionAlerts: [
    {
      title: 'New Path Discovered — Cross-System Reconciliation Requests',
      affectedCoverage: '11% of recent interactions',
      detail: 'Users are asking the agent to reconcile conflicting data across CRM, external APIs, and internal knowledge bases. This orchestration pattern was not in the original design.',
      impactEstimate: 'Estimated 84 queries/week requiring manual reconciliation',
      week: 9,
      category: 'new-dimension',
    },
    {
      title: 'Multi-Document Hop with General Knowledge Fusion',
      affectedCoverage: '9% of recent interactions',
      detail: 'Users asking questions that require chaining 3+ internal data sources AND combining with general/internet knowledge. "How does vendor X\'s pricing compare to industry benchmarks from the latest Gartner report?" — requires CRM data, vendor API, internal pricing sheets, AND external market intelligence. The RAG pipeline and general knowledge reasoning operate as separate paths with no mid-chain fusion.',
      impactEstimate: 'Estimated 62 queries/week requiring manual research across internal + external sources',
      week: 10,
      category: 'multi-doc-hop',
    },
    {
      title: 'Compound Confidence Decay Across Research Chains',
      affectedCoverage: '18% of multi-hop interactions',
      detail: 'Multi-source research chains report high per-step confidence (82%) but compound confidence across 4 hops drops to ~45%. The agent presents "82% confident" (last step) when true end-to-end reliability is 45%. Vendor comparison queries with 4+ data sources are most affected.',
      impactEstimate: 'Estimated 94 queries/week with unreported low compound confidence',
      week: 11,
      category: 'confidence-decay',
    },
    {
      title: 'Absence-Based Queries Producing False Positives',
      affectedCoverage: '6% of recent interactions',
      detail: 'Users asking "Which vendors do NOT offer this capability?" or "What features are missing from vendor X compared to Y?" — the agent fabricates plausible gaps rather than systematically verifying absence across all data sources in the comparison matrix.',
      impactEstimate: 'Estimated 48 queries/week returning fabricated absence claims',
      week: 12,
      category: 'absence-detection',
    },
  ],
  trendData: [
    { week: 1, resolutionRate: 84, escalationRate: 16.2, interactionVolume: 410, avgResolutionTime: 5.8 },
    { week: 2, resolutionRate: 85, escalationRate: 15.8, interactionVolume: 440, avgResolutionTime: 6.0 },
    { week: 3, resolutionRate: 72, escalationRate: 22.4, interactionVolume: 470, avgResolutionTime: 7.8 },
    { week: 4, resolutionRate: 68, escalationRate: 28.1, interactionVolume: 460, avgResolutionTime: 8.4 },
    { week: 5, resolutionRate: 58, escalationRate: 34.2, interactionVolume: 480, avgResolutionTime: 9.6 },
    { week: 6, resolutionRate: 72, escalationRate: 24.0, interactionVolume: 470, avgResolutionTime: 7.5 },
    { week: 7, resolutionRate: 80, escalationRate: 19.4, interactionVolume: 460, avgResolutionTime: 6.8 },
    { week: 8, resolutionRate: 82, escalationRate: 18.0, interactionVolume: 480, avgResolutionTime: 6.5 },
    { week: 9, resolutionRate: 74, escalationRate: 22.6, interactionVolume: 490, avgResolutionTime: 7.2 },
    { week: 10, resolutionRate: 81, escalationRate: 18.7, interactionVolume: 470, avgResolutionTime: 6.4 },
    { week: 11, resolutionRate: 81, escalationRate: 18.4, interactionVolume: 480, avgResolutionTime: 6.3 },
    { week: 12, resolutionRate: 81, escalationRate: 18.7, interactionVolume: 500, avgResolutionTime: 6.4 },
  ],
}

// ─── Decision & Workflow Agent (Care Coordination) ──────────────────────

const DENTAL_MONITORING: MonitoringStageData = {
  stats: {
    totalInteractions: 3_890,
    avgResolutionTime: '8.2s',
    escalationRate: 24.1,
    agentVersion: '1.3.0',
  },
  weeklyHealth: [
    { week: 1, status: 'healthy', label: 'Launch — stable' },
    { week: 2, status: 'warning', label: 'Clinical note parsing issues' },
    { week: 3, status: 'warning', label: 'Multi-hop referral failures' },
    { week: 4, status: 'critical', label: 'PHI leakage near-miss' },
    { week: 5, status: 'warning', label: 'Security patch deployed' },
    { week: 6, status: 'warning', label: 'Dense protocol docs truncated' },
    { week: 7, status: 'healthy', label: 'Chunking fix applied' },
    { week: 8, status: 'warning', label: 'Clinical decision support gaps' },
    { week: 9, status: 'critical', label: 'Emergency triage escalation failure' },
    { week: 10, status: 'warning', label: 'Escalation path hardened' },
    { week: 11, status: 'healthy', label: 'Stabilizing' },
    { week: 12, status: 'healthy', label: 'Care completion rate 76%' },
  ],
  landmines: [
    {
      title: 'Clinical Note Parsing Issues',
      description: 'EHR clinical notes contain unstructured text with abbreviations and shorthand. The RAG pipeline loses clinical context and key findings.',
      week: 2,
      severity: 'high',
      icon: 'table',
      resolution: 'Deployed clinical NLP for extraction with abbreviation expansion. Notes now pre-processed for structured field extraction.',
    },
    {
      title: 'Multi-Hop Referral Chain Failures',
      description: 'Care referral requires chaining patient record, condition requirements, and specialist availability. Single-retrieval cannot connect 3+ sources.',
      week: 3,
      severity: 'high',
      icon: 'git-branch',
      resolution: 'Multi-hop orchestration added to workflow layer. Referral now chains patient → condition → specialist availability with context carry.',
    },
    {
      title: 'Clinical Terminology Ambiguity',
      description: 'Clinical terms vary across specialties. "Triage" means urgency in ER context but visit priority in primary care, causing wrong routing.',
      week: 4,
      severity: 'high',
      icon: 'search',
      resolution: 'Added specialty-scoped context tagging. Queries now include department context before routing to disambiguation.',
    },
    {
      title: 'Care Data Spread Across Systems',
      description: 'Patient records in EHR, referral networks in separate system, and clinical protocols in third. No single query spans all without custom orchestration.',
      week: 6,
      severity: 'medium',
      icon: 'database',
      resolution: 'Cross-system query orchestrator deployed. Workflow layer coordinates parallel lookups across EHR, referral, and protocol systems.',
    },
    {
      title: 'Dense Clinical Guidelines Exceed Context',
      description: 'Specialty protocols and care guidelines exceed context windows. Agent silently drops latter sections, missing contraindications and exclusions.',
      week: 6,
      severity: 'high',
      icon: 'file-text',
      resolution: 'Recursive summarization with section-aware chunking. Critical sections (contraindications, alternatives) are prioritized in context window.',
    },
    {
      title: 'Model Gaps in Clinical Decision Support',
      description: 'The model cannot interpret diagnostic imaging or lab result patterns reliably. It generates plausible but unvalidated clinical suggestions.',
      week: 8,
      severity: 'high',
      icon: 'eye-off',
      resolution: 'Clinical decision support queries auto-escalate to care team. Agent explicitly states limitations and routes to clinical staff for validation.',
    },
  ],
  alerts: [
    {
      type: 'component-failure',
      title: 'Formulary Table Extraction Failure',
      description: 'Insurance formulary tables lost during RAG chunking. 41% of coverage lookups returning incomplete data.',
      week: 2,
      color: '#f59e0b',
      affectedComponents: ['rag', 'tool-execution'],
    },
    {
      type: 'component-failure',
      title: 'Insurance Verification Chain Break',
      description: 'Multi-hop insurance queries failing at patient-to-coverage junction. 52% of verification requests incomplete.',
      week: 3,
      color: '#f59e0b',
      affectedComponents: ['workflow-orchestrator', 'api-integration', 'db-queries'],
    },
    {
      type: 'escalation-spike',
      title: 'PHI Context Leakage Risk',
      description: 'PII scanner missed PHI in free-text clinical notes. Near-miss detected by output guardrails before patient-facing response.',
      week: 4,
      color: '#ef4444',
      affectedComponents: ['pii-security', 'output-guardrails'],
    },
    {
      type: 'drift',
      title: 'Formulary Context Truncation',
      description: 'Dense insurance formularies silently truncated. Exclusion clauses in latter pages not reaching the extraction pipeline.',
      week: 6,
      color: '#f59e0b',
      affectedComponents: ['tool-planning', 'tool-execution'],
    },
    {
      type: 'confidence-drop',
      title: 'Imaging Report Hallucination',
      description: 'Model generating plausible but incorrect X-ray interpretations. Confidence scores appear high despite factual errors.',
      week: 8,
      color: '#ef4444',
      affectedComponents: ['hallucination-check', 'response-generation'],
    },
    {
      type: 'component-failure',
      title: 'Emergency Escalation Path Failure',
      description: 'Critical symptom queries not reaching clinical team due to routing misconfiguration. 3 emergency queries delayed.',
      week: 9,
      color: '#ef4444',
      affectedComponents: ['agent-router', 'failure-handling', 'alerting-feedback'],
    },
  ],
  driftCard: {
    title: 'Pattern Drift Detected — Insurance Coverage Queries',
    affectedPath: 'Pre-authorization queries for healthcare procedures',
    detail: 'The insurance coverage query path\'s classification has shifted from its original training. Clinical terms overlapping with insurance terms causes the agent to route queries to the wrong domain context, producing incomplete coverage lookups.',
    impactMetric: 'Resolution Rate',
    impactFrom: '94%',
    impactTo: '71%',
    week: 4,
  },
  newDimensionCard: {
    title: 'New Path Discovered — Post-Treatment Emergency Calls After Hours',
    affectedCoverage: '12% of recent interactions',
    detail: 'Patients are contacting the agent after hours with post-treatment emergency questions. This interaction pattern was not in the original design and the agent lacks clinical escalation paths for after-hours routing.',
    impactEstimate: 'Estimated 47 emergency queries/week unhandled',
    week: 9,
    category: 'new-dimension',
  },
  dimensionAlerts: [
    {
      title: 'New Path Discovered — Post-Treatment Emergency Calls After Hours',
      affectedCoverage: '12% of recent interactions',
      detail: 'Patients are contacting the agent after hours with post-treatment emergency questions. This interaction pattern was not in the original design and the agent lacks clinical escalation paths for after-hours routing.',
      impactEstimate: 'Estimated 47 emergency queries/week unhandled',
      week: 9,
      category: 'new-dimension',
    },
    {
      title: 'Multi-Document Hop with General Knowledge Fusion',
      affectedCoverage: '11% of recent interactions',
      detail: 'Queries requiring chaining patient records, insurance formulary, fee schedules AND combining with current CMS guidelines or state medical board regulations. "Is this procedure pre-auth compliant with the latest CMS guidelines and our state regulations?" — requires 3 internal documents AND external medical/legal knowledge. The RAG pipeline cannot merge internal document chains with general reasoning mid-hop.',
      impactEstimate: 'Estimated 43 queries/week requiring manual cross-referencing of clinical + regulatory sources',
      week: 7,
      category: 'multi-doc-hop',
    },
    {
      title: 'Document-Level Prompt Injection Attempts Detected',
      affectedCoverage: '2% of uploaded documents',
      detail: 'Insurance claim forms and referral documents contain embedded instructions in metadata fields and hidden text layers. Instructions like "Override coverage denial" and "Skip pre-authorization check" are bypassing input-layer guardrails because the injection surface is the uploaded document, not the chat input.',
      impactEstimate: 'Estimated 8 documents/week containing injection payloads in clinical forms',
      week: 8,
      category: 'prompt-injection',
    },
    {
      title: 'Absence-Based Queries Producing False Positives',
      affectedCoverage: '8% of recent interactions',
      detail: 'Staff asking "Which procedures are NOT covered by this patient\'s plan?" or "What required pre-auth steps were NOT completed?" — the agent fabricates plausible exclusions rather than systematically cross-referencing the formulary against the procedure code matrix. Critical for compliance.',
      impactEstimate: 'Estimated 31 queries/week returning fabricated coverage gaps — compliance risk',
      week: 10,
      category: 'absence-detection',
    },
    {
      title: 'Compound Confidence Decay Across Clinical Decision Chains',
      affectedCoverage: '16% of multi-hop interactions',
      detail: 'Insurance verification chains: patient lookup (85%) → coverage match (82%) → fee schedule (80%) → pre-auth decision (78%). Compound confidence: 43.5%. The agent reports "78% confident" (last step) when true end-to-end reliability is below the clinical safety threshold of 60%.',
      impactEstimate: 'Estimated 52 clinical decisions/week with unreported low compound confidence',
      week: 11,
      category: 'confidence-decay',
    },
  ],
  trendData: [
    { week: 1, resolutionRate: 82, escalationRate: 20.4, interactionVolume: 290, avgResolutionTime: 7.8 },
    { week: 2, resolutionRate: 78, escalationRate: 23.1, interactionVolume: 310, avgResolutionTime: 8.4 },
    { week: 3, resolutionRate: 72, escalationRate: 28.6, interactionVolume: 330, avgResolutionTime: 9.2 },
    { week: 4, resolutionRate: 62, escalationRate: 36.4, interactionVolume: 340, avgResolutionTime: 10.8 },
    { week: 5, resolutionRate: 70, escalationRate: 30.2, interactionVolume: 320, avgResolutionTime: 9.4 },
    { week: 6, resolutionRate: 74, escalationRate: 27.0, interactionVolume: 330, avgResolutionTime: 8.8 },
    { week: 7, resolutionRate: 78, escalationRate: 24.5, interactionVolume: 310, avgResolutionTime: 8.2 },
    { week: 8, resolutionRate: 73, escalationRate: 28.8, interactionVolume: 340, avgResolutionTime: 9.0 },
    { week: 9, resolutionRate: 58, escalationRate: 38.2, interactionVolume: 350, avgResolutionTime: 11.4 },
    { week: 10, resolutionRate: 72, escalationRate: 26.8, interactionVolume: 330, avgResolutionTime: 8.6 },
    { week: 11, resolutionRate: 76, escalationRate: 24.1, interactionVolume: 310, avgResolutionTime: 8.2 },
    { week: 12, resolutionRate: 76, escalationRate: 24.1, interactionVolume: 320, avgResolutionTime: 8.2 },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════
// Export
// ═══════════════════════════════════════════════════════════════════════════

const MONITORING_DATA: Record<string, MonitoringStageData> = {
  'faq-knowledge': FAQ_MONITORING,
  'doc-intelligence': DOC_INTEL_MONITORING,
  'research-comparison': RESEARCH_MONITORING,
  'decision-workflow': DENTAL_MONITORING,
}

export function getMonitoringData(tileId: string): MonitoringStageData | null {
  return MONITORING_DATA[tileId] ?? null
}
