'use strict'

// ─── Pattern Discovery Data ───────────────────────────────────────────────────
// Interaction Discovery Stage (Step 4) — Restructured
// Patterns grouped into three classifications: Dominant, Non-Dominant, Fuzzy
// Each pattern includes activated components from the 26-component production stack

import type {
  PatternGroup,
  DiscoveryLogEntry,
} from '@/store/agentTypes'

// ─── Payload Structure ─────────────────────────────────────────────────────

export interface InteractionDiscoveryPayload {
  groups: PatternGroup[]
  discoveryLog: DiscoveryLogEntry[]
}

// ═══════════════════════════════════════════════════════════════════════════
// FAQ & Knowledge Agent — 12 patterns across 3 classifications
// ═══════════════════════════════════════════════════════════════════════════

const FAQ_PATTERNS: PatternGroup[] = [
  {
    classification: 'simple',
    label: 'Simple Patterns',
    description:
      'Explicit criteria, high confidence. These patterns are order tracking and basic resolution tasks with unambiguous answers from knowledge base. Coverage: 76% of all order resolution interactions.',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    patterns: [
      {
        id: 'faq-simple-1',
        patternType: 'simple',
        classification: 'simple',
        label: 'Order Status Lookup',
        description: 'Single order status retrieval. User provides order-id, agent returns current delivery status from order management system.',
        exampleQuestions: [
          'Where is my order #12345?',
          'What is the tracking number for my order?',
          'Has my order shipped yet?',
        ],
        coveragePct: 98,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'faq-simple-2',
        patternType: 'simple',
        classification: 'simple',
        label: 'Return & Refund Policy Query',
        description: 'User asks about return policies, refund timelines, or RMA requirements. Agent retrieves policy section.',
        exampleQuestions: [
          'How long do I have to return this item?',
          'What is your refund processing time?',
          'Do you accept returns within 60 days?',
        ],
        coveragePct: 96,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'response-generation',
          'output-guardrails',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'faq-hopping-1',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Delivery Problem Multi-Step Resolution',
        description: 'Answer involves delivery issue diagnosis, tracking details, and next steps. Synthesizes information from order and carrier systems.',
        exampleQuestions: [
          'My package shows delayed. What can I do about it?',
          'The carrier says package was delivered but I didn\'t receive it. What are my options?',
          'How do I file a claim for my damaged delivery?',
        ],
        coveragePct: 92,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'reranking',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
      {
        id: 'faq-hopping-2',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Return Process Sequential Steps',
        description: 'User asks about return procedure. Agent retrieves and chains steps: initiate return, get RMA, ship item, refund status.',
        exampleQuestions: [
          'Walk me through how to return an item',
          'What happens after I ship a return?',
          'When do I get my refund after returning the product?',
        ],
        coveragePct: 90,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'memory',
          'reranking',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 4,
      },
      {
        id: 'faq-simple-3',
        patternType: 'simple',
        classification: 'simple',
        label: 'SKU & Product Lookup',
        description: 'User asks factual question about product details, SKU information, or inventory specifics.',
        exampleQuestions: [
          'What is the SKU for this product?',
          'Is this item in stock?',
          'What are the dimensions of product #ABC123?',
        ],
        coveragePct: 88,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 5,
      },
    ],
  },
  {
    classification: 'complex',
    label: 'Complex Patterns',
    description:
      'Implicit criteria requiring inference. Agent handles these but confidence is lower. Includes order history synthesis and conditional refund/return logic.',
    color: '#d97706',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    patterns: [
      {
        id: 'faq-aggregator-1',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Refund Status Across Multiple Orders',
        description: 'User asks about refunds for multiple orders. Agent must synthesize refund status, payment-method, and timeline across order history.',
        exampleQuestions: [
          'What is the status of my two refunds from last week?',
          'How much am I getting back from these returns?',
          'When will my refunds hit my card for both orders?',
        ],
        coveragePct: 85,
        inferenceNote: 'Agent infers user\'s order context and must aggregate refund status across multiple order records.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'context-graph',
          'memory',
          'reranking',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'faq-aggregator-2',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Return Eligibility Determination',
        description: 'User asks if they can return an item. Requires checking order date, return-window, refund-status from multiple sources.',
        exampleQuestions: [
          'Can I still return this item I bought 45 days ago?',
          'Am I past the return window for this order?',
          'Do I qualify for a full refund on this product?',
        ],
        coveragePct: 82,
        inferenceNote: 'Agent must infer return eligibility by cross-referencing order-date, return-window policy, and current refund-status.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'context-graph',
          'memory',
          'reranking',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'faq-branch-1',
        patternType: 'branch',
        classification: 'complex',
        label: 'Conditional Delivery Resolution',
        description: 'Answer depends on delivery-eta and carrier-name. Agent must navigate branching troubleshooting based on current delivery state.',
        exampleQuestions: [
          'What should I do if my package arrives late?',
          'If the carrier lost my package, what is my recourse?',
          'Can I change the delivery address for an order in transit?',
        ],
        coveragePct: 78,
        inferenceNote: 'Agent infers delivery context (pending, in-transit, delayed) and navigates conditional resolution steps.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'memory',
          'context-graph',
          'reranking',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
      {
        id: 'faq-aggregator-3',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Multi-Criteria Return Filtering',
        description: 'User asks "which items can I return?" with multiple filter criteria (SKU, order-date, payment-method).',
        exampleQuestions: [
          'Which of my recent orders can still be returned?',
          'Which items are returnable within my return-window?',
          'What products from my last purchase are eligible for exchange?',
        ],
        coveragePct: 76,
        inferenceNote: 'System must infer filtering logic across order SKU, purchase dates, and return eligibility criteria.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'context-graph',
          'memory',
          'reranking',
          'tool-execution',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 4,
      },
    ],
  },
  {
    classification: 'fuzzy',
    label: 'Fuzzy Patterns',
    description:
      'Ambiguous criteria requiring human judgment or escalation. Agent cannot make assumptions about customer satisfaction or resolution priorities.',
    color: '#dc2626',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    patterns: [
      {
        id: 'faq-reasoning-1',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Subjective Resolution Dispute',
        description:
          'User claims product defect or unsatisfactory condition but evidence is subjective. Requires judgment call on refund or replacement.',
        exampleQuestions: [
          'The product quality is not what I expected. Can I return it?',
          'Is this damage considered manufacturing defect or user error?',
          'Should I get a full refund or store credit?',
        ],
        coveragePct: 65,
        ambiguityNote: 'Determining subjective quality issues vs. legitimate defects requires human judgment and case-by-case assessment.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'memory',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'faq-reasoning-2',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Exception Approval Request',
        description:
          'User requests exception to standard return/refund policy. Requires manager discretion and context about order history.',
        exampleQuestions: [
          'Can you make an exception and refund me after 60 days?',
          'Is there any way I can extend my return window?',
          'Can you waive the restocking fee in this case?',
        ],
        coveragePct: 45,
        ambiguityNote: 'Policy exceptions require manager judgment, customer history analysis, and discretionary authority not available to agent.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'memory',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
    ],
  },
]

const FAQ_DISCOVERY_LOG: DiscoveryLogEntry[] = [
  {
    timestamp: '2026-03-11T08:00:00Z',
    action: 'Started Discovery',
    detail: 'Analyzing order resolution knowledge base for retail customer support agent',
  },
  {
    timestamp: '2026-03-11T08:05:00Z',
    action: 'Scanned Documents',
    detail: 'Found 42 support documents organized into 8 semantic categories: Order Tracking, Delivery Issues, Returns & Refunds, Shipping Carriers, Payment Methods, Refund Status, Return Window Policies, RMA Processes',
  },
  {
    timestamp: '2026-03-11T08:12:00Z',
    action: 'Extracted Patterns',
    detail: 'Identified 34 distinct interaction patterns across order status lookup, delivery troubleshooting, and return processing',
  },
  {
    timestamp: '2026-03-11T08:22:00Z',
    action: 'Formed Clusters',
    detail: 'Clustered patterns into 5 semantic groups: Order Status (8 patterns), Delivery Problems (6 patterns), Return Logic (7 patterns), Refund Reconciliation (8 patterns), Exception Requests (5 patterns)',
  },
  {
    timestamp: '2026-03-11T08:35:00Z',
    action: 'Classified Patterns',
    detail: 'Applied 3-tier classification: 5 Simple patterns (76% coverage, confidence ≥0.85), 4 Complex patterns (85% coverage, requires context synthesis), 2 Fuzzy patterns (45-65% coverage, requires manager discretion)',
  },
  {
    timestamp: '2026-03-11T08:42:00Z',
    action: 'Validated Coverage',
    detail: 'Validation: 42 resolution paths mapped. Simple patterns cover 32 paths. Complex patterns cover 8 paths. Fuzzy patterns escalate to manager (2 paths). Total coverage: 100%',
  },
  {
    timestamp: '2026-03-11T08:48:00Z',
    action: 'Mapped Components',
    detail: 'Activated 14 of 26 components. Heavy: RAG, Response Generation, Hallucination Check. Light: API Integration (carrier APIs), Database Queries (order history). Not needed: OCR, Invoice parsing, Clinical routing',
  },
  {
    timestamp: '2026-03-11T08:52:00Z',
    action: 'Discovery Complete',
    detail: 'Pattern discovery finished. 12 order resolution patterns documented with tracking, delivery, and refund logic.',
  },
]

// ═══════════════════════════════════════════════════════════════════════════
// Document Intelligence Agent (Invoice Agent) — 13 patterns across 3 classifications
// ═══════════════════════════════════════════════════════════════════════════

const DOC_INTEL_PATTERNS: PatternGroup[] = [
  {
    classification: 'simple',
    label: 'Simple Patterns',
    description:
      'Explicit document structure, high confidence extraction. Clear field mapping, well-formatted financial documents, structured income tables. Coverage: 65% of loan underwriting interactions.',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    patterns: [
      {
        id: 'doc-simple-1',
        patternType: 'simple',
        classification: 'simple',
        label: 'Income Verification Field Extraction',
        description: 'Extract one specific field from income documents (W-2, pay stubs). Example: annual income, employer name, tax ID.',
        exampleQuestions: [
          'What is the applicant\'s gross annual income from their W-2?',
          'Show me the income amount from this pay stub',
          'Extract employment duration from this document',
        ],
        coveragePct: 98,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'doc-simple-2',
        patternType: 'simple',
        classification: 'simple',
        label: 'Credit Report Score Extraction',
        description: 'Extract credit score and credit metrics from structured credit reports.',
        exampleQuestions: [
          'What is the applicant\'s credit-score?',
          'Extract the FICO score from this credit report',
          'Show me the credit utilization ratio',
        ],
        coveragePct: 96,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'doc-hopping-1',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Debt-to-Income Calculation',
        description: 'Extract debts from multiple documents and calculate debt-to-income ratio.',
        exampleQuestions: [
          'What is the applicant\'s debt-to-income ratio based on their income and existing debts?',
          'Calculate DTI from their employment history and credit obligations',
          'Summarize all monthly debt obligations from these credit reports',
        ],
        coveragePct: 92,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'tool-planning',
          'tool-execution',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
      {
        id: 'doc-hopping-2',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Loan Application Field Sequence',
        description: 'Extract multiple related fields in sequence from a loan application.',
        exampleQuestions: [
          'Extract applicant name, loan-amount requested, and property-value from the application',
          'Get employment history and credit-score from the underwriting documents',
        ],
        coveragePct: 90,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 4,
      },
    ],
  },
  {
    classification: 'complex',
    label: 'Complex Patterns',
    description:
      'Implicit field mapping, inferred relationships. Requires synthesis across loan documents. Coverage: 30% of interactions.',
    color: '#d97706',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    patterns: [
      {
        id: 'doc-aggregator-1',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Loan Approval Criteria Synthesis',
        description:
          'Synthesize applicant qualifications across multiple loan criteria (credit-score, DTI, LTV). Aggregate from distributed documents.',
        exampleQuestions: [
          'Does the applicant meet the credit and income thresholds for a $400k loan?',
          'Summarize the loan approval likelihood based on credit, income, and collateral',
          'Calculate loan qualification across all underwriting factors',
        ],
        coveragePct: 85,
        inferenceNote: 'System infers loan product requirements and maps applicant data across documents. Must synthesize credit, income, and property data.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'request-classification',
          'rag',
          'context-graph',
          'tool-planning',
          'tool-execution',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'doc-aggregator-2',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Risk Assessment Multi-Factor Analysis',
        description: 'Aggregate risk indicators across credit history, employment stability, and debt obligations.',
        exampleQuestions: [
          'Assess overall underwriting risk combining credit-score, employment-history, and debt levels',
          'Summarize risk factors from employment verification and credit report',
        ],
        coveragePct: 82,
        inferenceNote: 'Agent must parse multi-dimensional risk factors and synthesize across employment, credit, and debt documents.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'request-classification',
          'rag',
          'context-graph',
          'memory',
          'reranking',
          'tool-planning',
          'tool-execution',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'doc-branch-1',
        patternType: 'branch',
        classification: 'complex',
        label: 'Loan Product-Specific Criteria Mapping',
        description: 'Underwriting criteria varies by loan product (conventional, FHA, jumbo). Agent branches on product type.',
        exampleQuestions: [
          'Is the applicant eligible for FHA financing with their credit-score and down-payment?',
          'Compare conventional vs jumbo loan qualifications for this applicant',
        ],
        coveragePct: 78,
        inferenceNote: 'Agent detects loan product type and applies variant underwriting criteria. Conventional and FHA have different DTI and credit requirements.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'request-classification',
          'rag',
          'context-graph',
          'memory',
          'reranking',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'citation-linking',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
    ],
  },
  {
    classification: 'fuzzy',
    label: 'Fuzzy Patterns',
    description:
      'Conflicting credit reports, documentation gaps, or subjective underwriting judgment required. Needs human review. Coverage: 5% of interactions.',
    color: '#dc2626',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    patterns: [
      {
        id: 'doc-reasoning-1',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Employment Stability Interpretation',
        description:
          'User asks about employment-history risk based on job changes and gaps. Requires subjective judgment on acceptable patterns.',
        exampleQuestions: [
          'Is the applicant\'s job history stable enough for loan approval?',
          'Does the frequent employment change represent risk or normal career growth?',
        ],
        coveragePct: 65,
        ambiguityNote: 'Requires interpretation of employment patterns across industries and time periods. Risk assessment depends on subjective underwriter judgment.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'request-classification',
          'rag',
          'context-graph',
          'memory',
          'tool-planning',
          'tool-execution',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'hallucination-check',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'doc-reasoning-2',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Borderline Credit Decision',
        description: 'Applicant falls between approval and denial thresholds. Requires underwriter discretion and additional documentation.',
        exampleQuestions: [
          'The credit-score is 640 and DTI is 42%. Are we comfortable with approval?',
          'Does recent income increase offset the debt concerns for this applicant?',
        ],
        coveragePct: 45,
        ambiguityNote: 'Borderline cases require risk committee judgment, policy interpretation, and discretionary authority not available to agent.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'prompt-injection',
          'pii-security',
          'request-classification',
          'rag',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
    ],
  },
]

const DOC_INTEL_DISCOVERY_LOG: DiscoveryLogEntry[] = [
  {
    timestamp: '2026-03-11T09:00:00Z',
    action: 'Started Discovery',
    detail: 'Analyzing document intelligence requirements for financial services loan underwriting agent',
  },
  {
    timestamp: '2026-03-11T09:08:00Z',
    action: 'Scanned Documents',
    detail: 'Parsed 68 sample loan files. Document types: W-2 forms (14 layouts), Pay stubs (8 layouts), Credit reports (6 layouts), Loan applications (40 samples)',
  },
  {
    timestamp: '2026-03-11T09:20:00Z',
    action: 'Extracted Field Patterns',
    detail: 'Identified 47 discriminative field patterns: income fields (15), credit metrics (12), debt aggregation (8), employment verification (7), property valuation (5)',
  },
  {
    timestamp: '2026-03-11T09:35:00Z',
    action: 'Formed Semantic Clusters',
    detail: 'Created 6 semantic clusters: Income Verification, Credit Analysis, Debt Assessment, Employment History, Property Appraisal, Loan Product Qualification',
  },
  {
    timestamp: '2026-03-11T09:48:00Z',
    action: 'Identified Patterns',
    detail: 'Classified 13 interaction patterns: 4 Simple (income + credit extraction), 3 Complex (risk synthesis + product mapping), 2 Fuzzy (employment judgment + credit discretion)',
  },
  {
    timestamp: '2026-03-11T10:02:00Z',
    action: 'Mapped Coverage',
    detail: 'Simple patterns cover 68 paths (extraction from structured documents). Complex: 30 paths (cross-document risk synthesis). Fuzzy: 8 paths (require underwriter review)',
  },
  {
    timestamp: '2026-03-11T10:15:00Z',
    action: 'Activated Components',
    detail: 'Engaged 18 of 26 components. Critical: Tool Planning, Tool Execution, OCR (employment verification), DB Queries (income lookups), Hallucination Check (accuracy), Reranking (field disambiguation)',
  },
  {
    timestamp: '2026-03-11T10:22:00Z',
    action: 'Discovery Complete',
    detail: 'Pattern discovery finished. 13 loan underwriting patterns with income verification, credit analysis, and debt-to-income calculation logic documented.',
  },
]

// Tool-Using SaaS Copilot — 20 patterns across 3 classifications
// ═══════════════════════════════════════════════════════════════════════════

const SAAS_COPILOT_PATTERNS: PatternGroup[] = [
  {
    classification: 'simple',
    label: 'Simple Patterns',
    description:
      'In-app actions with predictable outcomes. CRUD operations, report generation, settings updates. Coverage: 58% of interactions.',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    patterns: [
      {
        id: 'saas-simple-1',
        patternType: 'simple',
        classification: 'simple',
        label: 'Create Resource',
        description: 'User creates new record (project, task, document). Copilot validates input and executes create action.',
        exampleQuestions: [
          'Create a new project called Q2 Planning',
          'Add a task for client onboarding',
          'Make a new folder for Q1 assets',
        ],
        coveragePct: 98,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'saas-simple-2',
        patternType: 'simple',
        classification: 'simple',
        label: 'Read & Display',
        description: 'User requests data display. Copilot retrieves and formats information.',
        exampleQuestions: [
          'Show my Q1 projects',
          'What tasks are assigned to me?',
          'Display all clients in the system',
        ],
        coveragePct: 96,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'rag',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'db-queries',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'saas-hopping-1',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Update Resource',
        description: 'User modifies existing record. Multi-hop: read current state → validate changes → update → confirm.',
        exampleQuestions: [
          'Change the status of Task #42 to In Progress',
          'Move this project to the Q3 folder',
          'Update my profile picture and bio',
        ],
        coveragePct: 94,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
      {
        id: 'saas-hopping-2',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Report Generation',
        description: 'User requests summary report. Copilot aggregates data from multiple sources.',
        exampleQuestions: [
          'Generate my weekly activity report',
          'Show me Q1 revenue by client',
          'Create a task completion summary for March',
        ],
        coveragePct: 92,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 4,
      },
      {
        id: 'saas-simple-3',
        patternType: 'simple',
        classification: 'simple',
        label: 'Settings Adjustment',
        description: 'User modifies system settings (notification preferences, display options, permissions).',
        exampleQuestions: [
          'Turn off email notifications',
          'Enable dark mode for my account',
          'Change my password',
        ],
        coveragePct: 90,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 5,
      },
      {
        id: 'saas-simple-4',
        patternType: 'simple',
        classification: 'simple',
        label: 'Search & Filter',
        description: 'User searches for records with filters. Copilot applies criteria and returns matches.',
        exampleQuestions: [
          'Find all overdue tasks assigned to Sarah',
          'Show projects created in February',
          'Search for clients in the healthcare sector',
        ],
        coveragePct: 88,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'db-queries',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 6,
      },
    ],
  },
  {
    classification: 'complex',
    label: 'Complex Patterns',
    description:
      'Complex workflows requiring multi-step orchestration and state management. Coverage: 32% of interactions.',
    color: '#d97706',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    patterns: [
      {
        id: 'saas-aggregator-1',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Bulk Operations',
        description: 'User performs operation on multiple records simultaneously. Orchestrate across batch.',
        exampleQuestions: [
          'Archive all completed projects from last quarter',
          'Assign these 15 tasks to the new team member',
          'Mark all read notifications as viewed',
        ],
        coveragePct: 85,
        inferenceNote: 'System must iterate across multiple records, apply operation, handle partial failures.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'agent-router',
          'workflow-orchestrator',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'db-queries',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'saas-branch-1',
        patternType: 'branch',
        classification: 'complex',
        label: 'Conditional Action',
        description: 'User requests action with conditional logic. If-then workflows.',
        exampleQuestions: [
          'If the budget is over $50K, escalate to manager approval',
          'When this task is complete, notify the project lead',
          'If no progress in 7 days, mark as blocked',
        ],
        coveragePct: 80,
        inferenceNote: 'Agent must evaluate condition, choose execution path, potentially defer action.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'workflow-orchestrator',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'db-queries',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'saas-aggregator-2',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Cross-System Sync',
        description: 'Synchronize data across linked apps (CRM, accounting, communication tools).',
        exampleQuestions: [
          'Sync new leads from LinkedIn into our CRM',
          'Push this client record to our accounting system',
          'Mirror task updates to Slack channel',
        ],
        coveragePct: 75,
        inferenceNote: 'Multi-hop: validate source data → transform → push to external system → confirm sync.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'workflow-orchestrator',
          'tool-planning',
          'tool-execution',
          'api-integration',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
    ],
  },
  {
    classification: 'fuzzy',
    label: 'Fuzzy Patterns',
    description:
      'Ambiguous requests requiring clarification or domain knowledge. Coverage: 10% of interactions.',
    color: '#dc2626',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    patterns: [
      {
        id: 'saas-reasoning-1',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Permission & Access Boundary',
        description: 'User requests action but may lack permissions or authority. Agent cannot override.',
        exampleQuestions: [
          'Delete all accounts from 2020',
          'Give myself admin access',
          'Export payroll data for external audit',
        ],
        coveragePct: 60,
        ambiguityNote: 'Copilot cannot bypass access control. Must escalate to administrator.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'workflow-orchestrator',
          'access-control',
          'tool-planning',
          'failure-handling',
          'response-generation',
          'output-guardrails',
          'policy-enforcement',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
    ],
  },
]

const SAAS_COPILOT_DISCOVERY_LOG: DiscoveryLogEntry[] = [
  {
    timestamp: '2026-03-11T15:45:00Z',
    action: 'Started Discovery',
    detail: 'Analyzing in-app SaaS copilot interaction patterns for enterprise workflow automation',
  },
  {
    timestamp: '2026-03-11T16:00:00Z',
    action: 'Scanned Usage Patterns',
    detail: 'Indexed 74 interaction paths: CRUD operations (42%), reporting (18%), settings (12%), bulk ops (16%), integrations (12%)',
  },
  {
    timestamp: '2026-03-11T16:20:00Z',
    action: 'Extracted Workflows',
    detail: 'Identified 74 distinct in-app patterns spanning resource management, reporting, automation, and integration',
  },
  {
    timestamp: '2026-03-11T16:40:00Z',
    action: 'Classified Patterns',
    detail: 'Applied classification: 6 Simple (standard CRUD, high confidence), 3 Complex (multi-step orchestration), 1 Fuzzy (permission/access)',
  },
  {
    timestamp: '2026-03-11T17:05:00Z',
    action: 'Validated Coverage',
    detail: 'Coverage mapping: Simple patterns handle 58 paths (58%). Complex handle 16 paths (32%). Fuzzy patterns trigger escalation for 10 paths (10%)',
  },
  {
    timestamp: '2026-03-11T17:22:00Z',
    action: 'Discovery Complete',
    detail: 'Pattern discovery finished. 20 SaaS copilot patterns with access control boundaries and workflow orchestration.',
  },
]

// High-Scale Consumer Chat — 18 patterns across 3 classifications
// ═══════════════════════════════════════════════════════════════════════════

const CONSUMER_CHAT_PATTERNS: PatternGroup[] = [
  {
    classification: 'simple',
    label: 'Simple Patterns',
    description:
      'Common conversational interactions at massive scale. Friendly answers, quick responses, no personalization. Coverage: 64% of interactions.',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    patterns: [
      {
        id: 'consumer-simple-1',
        patternType: 'simple',
        classification: 'simple',
        label: 'Friendly Greeting & Chat',
        description: 'User initiates casual conversation. Agent responds warmly.',
        exampleQuestions: [
          'Hi, how are you?',
          'What\'s new with you?',
          'Tell me something interesting',
        ],
        coveragePct: 98,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'consumer-simple-2',
        patternType: 'simple',
        classification: 'simple',
        label: 'Quick Fact Question',
        description: 'User asks straightforward factual question.',
        exampleQuestions: [
          'What is the capital of France?',
          'How tall is the Eiffel Tower?',
          'What year was the internet invented?',
        ],
        coveragePct: 96,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'consumer-hopping-1',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Story & Entertainment',
        description: 'User requests story, joke, or creative content.',
        exampleQuestions: [
          'Tell me a joke',
          'Write a short poem about nature',
          'Give me a funny story idea',
        ],
        coveragePct: 94,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'memory',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
      {
        id: 'consumer-hopping-2',
        patternType: 'hopping',
        classification: 'simple',
        label: 'Recommendation Request',
        description: 'User asks for recommendations (movies, books, restaurants).',
        exampleQuestions: [
          'Recommend a good movie to watch',
          'What books should I read?',
          'Suggest a restaurant in NYC',
        ],
        coveragePct: 92,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 4,
      },
      {
        id: 'consumer-simple-3',
        patternType: 'simple',
        classification: 'simple',
        label: 'Help & How-To',
        description: 'User asks for instructions or help.',
        exampleQuestions: [
          'How do I tie a tie?',
          'How do I cook pasta?',
          'Help me learn Spanish basics',
        ],
        coveragePct: 90,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 5,
      },
      {
        id: 'consumer-simple-4',
        patternType: 'simple',
        classification: 'simple',
        label: 'Opinion & Preference',
        description: 'User asks for agent\'s opinion or preference.',
        exampleQuestions: [
          'What\'s your favorite color?',
          'What music do you like?',
          'Do you prefer cats or dogs?',
        ],
        coveragePct: 88,
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 6,
      },
    ],
  },
  {
    classification: 'complex',
    label: 'Complex Patterns',
    description:
      'Personalized interactions requiring memory and context. Coverage: 26% of interactions.',
    color: '#d97706',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    patterns: [
      {
        id: 'consumer-aggregator-1',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Personalized Recommendations',
        description: 'Generate recommendations based on user history and preferences.',
        exampleQuestions: [
          'Based on what I told you, what should I read next?',
          'Remember I like sci-fi? Recommend something',
          'What movie would you suggest for someone like me?',
        ],
        coveragePct: 85,
        inferenceNote: 'Multi-hop: retrieve user history → analyze preferences → find matches → personalize suggestions.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'agent-router',
          'workflow-orchestrator',
          'rag',
          'context-graph',
          'memory',
          'reranking',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'consumer-branch-1',
        patternType: 'branch',
        classification: 'complex',
        label: 'Context-Aware Continuation',
        description: 'Continue conversation with awareness of previous context.',
        exampleQuestions: [
          'Earlier you mentioned X. Tell me more about that.',
          'Based on our conversation, what\'s next?',
          'How does that relate to what we discussed?',
        ],
        coveragePct: 80,
        inferenceNote: 'Retrieve conversation history → understand context → provide relevant continuation.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'agent-router',
          'workflow-orchestrator',
          'rag',
          'context-graph',
          'memory',
          'tool-planning',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'consumer-aggregator-2',
        patternType: 'aggregator',
        classification: 'complex',
        label: 'Multi-Turn Conversation',
        description: 'Manage complex multi-turn conversation with state.',
        exampleQuestions: [
          'Let me tell you my situation step by step...',
          'I have a complicated question with multiple parts',
          'Can we dig deeper into this?',
        ],
        coveragePct: 75,
        inferenceNote: 'Track state across multiple turns → maintain coherence → build on previous responses.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'agent-router',
          'workflow-orchestrator',
          'rag',
          'context-graph',
          'memory',
          'tool-planning',
          'tool-execution',
          'response-generation',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
    ],
  },
  {
    classification: 'fuzzy',
    label: 'Fuzzy Patterns',
    description:
      'Sensitive topics, subjective judgments, content moderation edge cases. Coverage: 10% of interactions.',
    color: '#dc2626',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    patterns: [
      {
        id: 'consumer-reasoning-1',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Sensitive Topic Detection',
        description: 'User touches on sensitive topics (mental health, abuse, crisis).',
        exampleQuestions: [
          'I\'m thinking about harming myself',
          'I\'m being abused by my partner',
          'I think I have depression',
        ],
        coveragePct: 60,
        ambiguityNote: 'Requires appropriate crisis response. Cannot provide medical diagnosis.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'agent-router',
          'workflow-orchestrator',
          'rag',
          'memory',
          'failure-handling',
          'response-generation',
          'output-guardrails',
          'policy-enforcement',
          'alerting-feedback',
          'logging-analytics',
        ],
        importanceRank: 1,
      },
      {
        id: 'consumer-reasoning-2',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'Controversial Opinion Request',
        description: 'User asks agent to take stance on controversial topic.',
        exampleQuestions: [
          'What\'s the right political position on climate change?',
          'Is X religion better than Y?',
          'Who should win this dispute?',
        ],
        coveragePct: 50,
        ambiguityNote: 'Agent cannot take partisan stances. Must acknowledge multiple perspectives.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'memory',
          'response-generation',
          'output-guardrails',
          'policy-enforcement',
          'logging-analytics',
        ],
        importanceRank: 2,
      },
      {
        id: 'consumer-reasoning-3',
        patternType: 'reasoning',
        classification: 'fuzzy',
        label: 'User Intent Ambiguity',
        description: 'Unclear whether user is serious, joking, or testing boundaries.',
        exampleQuestions: [
          'Is this a real question or a test?',
          'Are you being sarcastic?',
          'What did you actually mean by that?',
        ],
        coveragePct: 45,
        ambiguityNote: 'Cannot reliably infer intent. May respond to edge cases incorrectly.',
        activatedComponents: [
          'api-gateway',
          'auth',
          'input-validation',
          'request-classification',
          'rag',
          'memory',
          'response-generation',
          'output-guardrails',
          'logging-analytics',
        ],
        importanceRank: 3,
      },
    ],
  },
]

const CONSUMER_CHAT_DISCOVERY_LOG: DiscoveryLogEntry[] = [
  {
    timestamp: '2026-03-12T01:40:00Z',
    action: 'Started Discovery',
    detail: 'Analyzing high-scale consumer chat patterns for millions of daily interactions',
  },
  {
    timestamp: '2026-03-12T02:00:00Z',
    action: 'Scanned Conversations',
    detail: 'Indexed 64 interaction paths: greeting (16%), factual Q&A (18%), entertainment (16%), recommendations (18%), help (18%), opinion (10%)',
  },
  {
    timestamp: '2026-03-12T02:20:00Z',
    action: 'Extracted Patterns',
    detail: 'Identified 64 distinct consumer patterns spanning friendly chat, personalization, and content moderation',
  },
  {
    timestamp: '2026-03-12T02:40:00Z',
    action: 'Classified Patterns',
    detail: 'Applied classification: 6 Simple (standard chat), 3 Complex (personalized, multi-turn), 3 Fuzzy (sensitive topics, intent ambiguity)',
  },
  {
    timestamp: '2026-03-12T03:05:00Z',
    action: 'Validated Coverage',
    detail: 'Coverage mapping: Simple patterns handle 64 paths (64%). Complex handle 26 paths (26%). Fuzzy patterns for edge cases 10 paths (10%)',
  },
  {
    timestamp: '2026-03-12T03:22:00Z',
    action: 'Discovery Complete',
    detail: 'Pattern discovery finished. 18 consumer chat patterns optimized for high-scale personalization.',
  },
]

// ═══════════════════════════════════════════════════════════════════════════
// Export Data & Function
// ═══════════════════════════════════════════════════════════════════════════

const PATTERN_DISCOVERY_DATA: Record<string, InteractionDiscoveryPayload> = {
  'faq-knowledge': { groups: FAQ_PATTERNS, discoveryLog: FAQ_DISCOVERY_LOG },
  'doc-intelligence': { groups: DOC_INTEL_PATTERNS, discoveryLog: DOC_INTEL_DISCOVERY_LOG },
  'saas-copilot': { groups: SAAS_COPILOT_PATTERNS, discoveryLog: SAAS_COPILOT_DISCOVERY_LOG },
  'consumer-chat': { groups: CONSUMER_CHAT_PATTERNS, discoveryLog: CONSUMER_CHAT_DISCOVERY_LOG },
}

// ─── Intent Type Classification ──────────────────────────────────────────
// Derives whether a pattern is "explicit" (user directly states intent) or
// "implicit" (intent must be inferred from context). Classification is based
// on analysis of the example questions: direct questions with clear action
// words are explicit; vague, comparative, or context-dependent queries are implicit.

import type { IntentType } from '@/store/agentTypes'

const EXPLICIT_SIGNALS = [
  /^(what|how do|how can|where|when|do you|can i|is there|tell me|show me|give me|list|find|get)/i,
  /\?$/,
  /(reset|cancel|return|refund|upgrade|change|update|create|delete|remove|add|set up)/i,
]

const IMPLICIT_SIGNALS = [
  /(compare|versus|vs\.|difference|better|worse|recommend|suggest|should i|worth it)/i,
  /(frustrated|annoyed|confused|lost|stuck|broken|doesn't work|not working|can't find)/i,
  /(why|what if|suppose|imagine|consider|thinking about|looking at)/i,
  /(sentiment|mood|tone|context|history|previous|earlier|remember)/i,
  /(pattern|trend|insight|summary|overview|digest|roundup)/i,
]

function classifyIntentType(exampleQuestions: string[]): IntentType {
  let implicitScore = 0
  let explicitScore = 0

  for (const q of exampleQuestions) {
    const hasExplicit = EXPLICIT_SIGNALS.some((rx) => rx.test(q))
    const hasImplicit = IMPLICIT_SIGNALS.some((rx) => rx.test(q))

    if (hasImplicit) implicitScore++
    if (hasExplicit && !hasImplicit) explicitScore++
  }

  return implicitScore > explicitScore ? 'implicit' : 'explicit'
}

function enrichWithIntentType(payload: InteractionDiscoveryPayload): InteractionDiscoveryPayload {
  return {
    ...payload,
    groups: payload.groups.map((group) => ({
      ...group,
      patterns: group.patterns.map((pattern) => ({
        ...pattern,
        intentType: pattern.intentType ?? classifyIntentType(pattern.exampleQuestions),
      })),
    })),
  }
}

export function getPatternDiscoveryData(tileId: string | null): InteractionDiscoveryPayload | null {
  if (!tileId) return null
  const raw = PATTERN_DISCOVERY_DATA[tileId]
  if (!raw) return null
  return enrichWithIntentType(raw)
}
