/**
 * Synthetic Test Data V3 - VibeModel Agent Playground V3
 * Provides test queries and coverage metrics for each agent tile
 * Data extracted from Sections 5.1-5.2 of use case markdown files
 */

export interface SyntheticTestV3 {
  id: string
  query: string
  patternTested: string
  dimensionsCrossed: string[]
  expectedBehavior: string
  difficulty: 'simple' | 'complex' | 'reasoning'
  tier: 'green' | 'amber' | 'red'
}

export interface TestCoverageV3 {
  totalTests: number
  coveragePercent: number
  tests: SyntheticTestV3[]
}

/**
 * Get synthetic test data for a given tile ID
 */
export function getSyntheticTestDataV3(tileId: string): TestCoverageV3 | null {
  const testDatabase: Record<string, TestCoverageV3> = {
    'doc-intelligence': {
      totalTests: 108,
      coveragePercent: 94,
      tests: [
        {
          id: 'invoice-q1',
          query: 'What was our AWS S3 storage cost in February 2026?',
          patternTested: 'pat-001-S',
          dimensionsCrossed: ['dim-006', 'fmt-001', 'tool-aws'],
          expectedBehavior: '$4,287.63, day-over-day rate, YoY comparison, source citation AWS-2026-02',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'invoice-q2',
          query: 'How many Staples invoices did we receive in Q4 2025?',
          patternTested: 'pat-002-S',
          dimensionsCrossed: ['dim-001', 'fmt-004', 'tool-pdf'],
          expectedBehavior: '8 invoices (Oct 2, Nov 2, Dec 4), invoice numbers, 286 total line items',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'invoice-q3',
          query: 'What is GCP\'s committed use discount from our contracts?',
          patternTested: 'pat-003-S',
          dimensionsCrossed: ['dim-019', 'fmt-002', 'tool-sql'],
          expectedBehavior: '$12,450 annual CUD amount, expires Jan 2027, 25% discount rate',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'invoice-q4',
          query: 'Show all office supplies purchased over $5,000 in the past 6 months',
          patternTested: 'pat-004-S',
          dimensionsCrossed: ['dim-003', 'fmt-004', 'tool-pdf'],
          expectedBehavior: '3 items: desk $5,840, chairs $6,230, tech bundle $5,105, with dates/invoice #s',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'invoice-q5',
          query: 'List all vendors we use across cost data',
          patternTested: 'pat-005-S',
          dimensionsCrossed: ['dim-031', 'fmt-001', 'fmt-002', 'fmt-004'],
          expectedBehavior: 'AWS, GCP, Staples (3 vendors) with invoice counts and total spend per vendor',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'invoice-q6',
          query: 'Match each Staples invoice from October 2025 to its corresponding PO',
          patternTested: 'pat-009-C',
          dimensionsCrossed: ['dim-002', 'dim-019', 'fmt-004', 'fmt-002'],
          expectedBehavior: '2 invoices matched to POs SP-2025-0847, SP-2025-0902 (98%+ confidence)',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q7',
          query: 'Which AWS service costs appear in our purchase order database, and which don\'t?',
          patternTested: 'pat-010-C',
          dimensionsCrossed: ['dim-006', 'dim-019', 'fmt-001', 'fmt-002'],
          expectedBehavior: '156 items total, 149 matched (95.5%), 7 unmatched with explanations',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q8',
          query: 'Compare AWS S3 storage costs to GCP Cloud Storage costs per GB for Q4 2025',
          patternTested: 'pat-011-C',
          dimensionsCrossed: ['dim-031', 'dim-032', 'fmt-001', 'fmt-003'],
          expectedBehavior: 'AWS $0.023/GB vs GCP $0.020/GB (13% savings), with regional caveats',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q9',
          query: 'Show month-by-month cost breakdown for Q4 2025 across all vendors',
          patternTested: 'pat-014-C',
          dimensionsCrossed: ['dim-033', 'dim-034', 'fmt-001', 'fmt-003', 'fmt-004'],
          expectedBehavior: 'Oct $10,234 (AWS $6,145 + GCP $2,890 + Staples $1,199), plus Nov/Dec with MoM %',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q10',
          query: 'Calculate total storage costs (S3, EBS, Cloud Storage, Backup) for Q4 2025',
          patternTested: 'pat-017-C',
          dimensionsCrossed: ['dim-032', 'dim-034', 'fmt-001', 'fmt-003', 'fmt-004'],
          expectedBehavior: '$32,847.92 total (AWS $18,456 + GCP $9,234 + Staples $5,157), 100% completeness',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q11',
          query: 'Which cost categories showed growth above 20% from Q3 to Q4 2025?',
          patternTested: 'pat-018-R',
          dimensionsCrossed: ['dim-035', 'dim-031', 'dim-034', 'fmt-001', 'fmt-003', 'fmt-004'],
          expectedBehavior: '2 categories: Data Transfer +27.3%, Compute Engine +22.1%, with month-by-month breakdown',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q12',
          query: 'AWS data transfer costs spiked in September 2025. What caused it and when did it resolve?',
          patternTested: 'pat-019-R',
          dimensionsCrossed: ['dim-036', 'dim-035', 'dim-031', 'fmt-001'],
          expectedBehavior: '329% spike, root cause: data migration INFRA-2025-Q3-MIGRATION (Sept 1-25), 96% confidence',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q13',
          query: 'Should we renegotiate our GCP contract based on recent usage trends?',
          patternTested: 'pat-020-R',
          dimensionsCrossed: ['dim-035', 'dim-031', 'dim-019', 'dim-027'],
          expectedBehavior: 'Recommendation to negotiate higher CUD (projected $182K annually), medium confidence',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q14',
          query: 'Validate all invoice charges from Q4 2025 against their purchase orders. Flag any discrepancies.',
          patternTested: 'pat-022-R',
          dimensionsCrossed: ['dim-002', 'dim-003', 'dim-019', 'dim-027', 'dim-034'],
          expectedBehavior: '847 items, 821 matched (97%), 18 discrepancies (2%), 8 no-PO (1%), none >$10K',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q15',
          query: 'Identify seasonal cost patterns in our historical data and project next year\'s costs',
          patternTested: 'pat-023-R',
          dimensionsCrossed: ['dim-036', 'dim-035', 'dim-037', 'dim-034'],
          expectedBehavior: 'Q4 18-22% higher than baseline, projection $145K-$156K for next year Q4, medium confidence',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q16',
          query: 'How much have we spent with each vendor year-to-date (March 2025 - Feb 2026)?',
          patternTested: 'pat-015-C',
          dimensionsCrossed: ['dim-031', 'dim-033', 'fmt-001', 'fmt-003', 'fmt-004'],
          expectedBehavior: 'AWS $89,456 (62%), GCP $38,234 (26%), Staples $16,457 (11%), Feb incomplete note',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q17',
          query: 'Archive invoices from 2020 show lower costs. Are we being overcharged now?',
          patternTested: 'pat-020-R',
          dimensionsCrossed: ['dim-035', 'dim-031', 'fmt-001', 'fmt-003'],
          expectedBehavior: 'Efficiency improved 60% (per compute-hour), not overcharged, 82% confidence (2020 incomplete)',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q18',
          query: 'Which Staples invoices from Q4 2025 could not be matched to purchase orders?',
          patternTested: 'pat-013-C',
          dimensionsCrossed: ['dim-002', 'dim-019', 'fmt-004', 'fmt-002'],
          expectedBehavior: '1 of 8 unmatched (SP-2025-1934, $857), recommend retroactive PO or exception, 91% confidence',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'invoice-q19',
          query: 'Generate a complete cost reconciliation report for Q4 2025 ready for finance sign-off',
          patternTested: 'pat-025-R',
          dimensionsCrossed: ['dim-034', 'dim-031', 'dim-019', 'fmt-001', 'fmt-003', 'fmt-004'],
          expectedBehavior: 'Multi-part report: exec summary, vendor breakdown, validation (97% matched), no critical anomalies',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'invoice-q20',
          query: 'What is our monthly burn rate trending, and when will we exceed the annual budget of $175K?',
          patternTested: 'pat-024-R',
          dimensionsCrossed: ['dim-034', 'dim-031', 'dim-019', 'fmt-001', 'fmt-003', 'fmt-004'],
          expectedBehavior: 'Projected $139K-$154K (under budget), current trajectory 86%, monitor data transfer costs',
          difficulty: 'reasoning',
          tier: 'red',
        },
      ],
    },
    'saas-copilot': {
      totalTests: 69,
      coveragePercent: 91,
      tests: [
        {
          id: 'saas-q1',
          query: 'What plan am I on?',
          patternTested: 'pat-001-S',
          dimensionsCrossed: ['dim-001', 'cust-dim-002', 'tool-db'],
          expectedBehavior: 'Return: Pro plan, $4,200/month',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'saas-q2',
          query: 'How do I reset password?',
          patternTested: 'pat-002-S',
          dimensionsCrossed: ['dim-007', 'kb-dim-002', 'tool-kb'],
          expectedBehavior: 'Return: Top KB article (kb-0147) with step-by-step instructions',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'saas-q3',
          query: 'Is my account active?',
          patternTested: 'pat-003-S',
          dimensionsCrossed: ['dim-001', 'cust-dim-005', 'tool-db'],
          expectedBehavior: 'Return: Active, last login timestamp',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'saas-q4',
          query: 'Reset my password',
          patternTested: 'pat-006-A',
          dimensionsCrossed: ['dim-011', 'dim-015', 'cust-dim-005', 'tool-db', 'tool-api'],
          expectedBehavior: 'Return: Email sent, reset link valid 24h, action confirmed',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'saas-q5',
          query: 'Upgrade to Enterprise',
          patternTested: 'pat-007-A',
          dimensionsCrossed: ['dim-012', 'dim-015', 'cust-dim-002', 'tool-db', 'tool-api'],
          expectedBehavior: 'Return: Upgraded, features active, invoice sent, action confirmed',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'saas-q6',
          query: 'Reset password but account suspended',
          patternTested: 'pat-010-A',
          dimensionsCrossed: ['dim-011', 'dim-015', 'cust-dim-005', 'tool-db', 'tool-api'],
          expectedBehavior: 'Return: Cannot reset (account suspended due to overdue payment), action blocked',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'saas-q7',
          query: 'Service is down!',
          patternTested: 'pat-014-C',
          dimensionsCrossed: ['dim-002', 'dim-003', 'dim-020', 'kb-dim-008', 'tool-kb'],
          expectedBehavior: 'Detect P1 urgency, escalate to Engineering, ticket #SUP-2026-08932',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'saas-q8',
          query: 'Bill seems high',
          patternTested: 'pat-016-C',
          dimensionsCrossed: ['dim-001', 'dim-002', 'dim-020', 'cust-dim-003', 'tool-kb', 'tool-db'],
          expectedBehavior: 'Query usage, escalate to Billing with context summary',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'saas-q9',
          query: 'Want custom features',
          patternTested: 'pat-015-C',
          dimensionsCrossed: ['dim-001', 'dim-002', 'dim-021', 'cust-dim-002', 'tool-db'],
          expectedBehavior: 'Detect upsell signal, escalate to Sales with account info',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'saas-q10',
          query: 'Can\'t log in, confused about suspension',
          patternTested: 'pat-012-C',
          dimensionsCrossed: ['dim-001', 'dim-002', 'dim-020', 'cust-dim-005', 'cust-dim-006'],
          expectedBehavior: 'Context enriched escalation to Billing, empathetic tone',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'saas-q11',
          query: 'Performance issues on reports, already tried KB article',
          patternTested: 'pat-018-R',
          dimensionsCrossed: ['dim-001', 'dim-002', 'dim-004', 'dim-008', 'kb-dim-008', 'tool-kb', 'tool-db'],
          expectedBehavior: 'Multi-step escalation to Engineering with attempt history',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'saas-q12',
          query: 'Angry customer, poor satisfaction history',
          patternTested: 'pat-022-R',
          dimensionsCrossed: ['dim-017', 'dim-001', 'dim-002', 'dim-003', 'dim-020', 'cust-dim-009'],
          expectedBehavior: 'Churn signal detection with de-escalation attempt',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'saas-q13',
          query: 'Data export + understand privacy implications',
          patternTested: 'pat-023-R',
          dimensionsCrossed: ['dim-014', 'dim-001', 'dim-002', 'dim-019', 'cust-dim-001', 'cust-dim-004'],
          expectedBehavior: 'Multi-purpose escalation to General Support with privacy context',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'saas-q14',
          query: 'Using 8,200 API calls/day, confused about rate limits',
          patternTested: 'pat-013-C',
          dimensionsCrossed: ['dim-001', 'dim-002', 'dim-004', 'cust-dim-002', 'cust-dim-009'],
          expectedBehavior: 'Education + escalation to Engineering with usage breakdown',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'saas-q15',
          query: 'Multiple issues in one ticket: password reset + billing + feature request',
          patternTested: 'pat-021-R',
          dimensionsCrossed: ['dim-001', 'dim-002', 'dim-003', 'dim-010', 'dim-011', 'cust-dim-001'],
          expectedBehavior: 'Routing to General Support with action items + escalations',
          difficulty: 'reasoning',
          tier: 'red',
        },
      ],
    },
    'research-comparison': {
      totalTests: 100,
      coveragePercent: 92,
      tests: [
        {
          id: 'rag-q1',
          query: 'What is our API rate limiting policy?',
          patternTested: 'pat-001-S',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-conf'],
          expectedBehavior: 'Confluence page title, current version, last modified, full text, source link',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'rag-q2',
          query: 'Who is the head of the Product team?',
          patternTested: 'pat-002-S',
          dimensionsCrossed: ['dim-005', 'dim-010', 'fmt-005', 'tool-sql'],
          expectedBehavior: 'Person name, title, email, office, direct reports count, source: Directory',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'rag-q3',
          query: 'List all open issues assigned to Sarah Chen in Jira',
          patternTested: 'pat-003-S',
          dimensionsCrossed: ['dim-005', 'dim-009', 'fmt-004', 'tool-jira'],
          expectedBehavior: '4-6 open issues, IDs, summaries, due dates, project codes',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'rag-q4',
          query: 'What is our company\'s PTO policy?',
          patternTested: 'pat-005-S',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-conf'],
          expectedBehavior: 'Confluence HR page link, policy text (annual days, accrual, approval), updated date',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'rag-q5',
          query: 'Show me all Confluence spaces',
          patternTested: 'pat-004-S',
          dimensionsCrossed: ['dim-006', 'fmt-001', 'tool-conf'],
          expectedBehavior: '45 spaces listed with name, key, page count, last activity date',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'rag-q6',
          query: 'For the payment system redesign project, show related docs, Jira epics, and Slack discussions',
          patternTested: 'pat-009-C',
          dimensionsCrossed: ['dim-001', 'dim-011', 'dim-019', 'fmt-001', 'fmt-004', 'fmt-002'],
          expectedBehavior: 'ADR-2025-047 + ENG-1847 + #eng-payments Slack thread, synthesized with decision date/status',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q7',
          query: 'Which proposals in Drive relate to the API redesign initiative?',
          patternTested: 'pat-010-C',
          dimensionsCrossed: ['dim-001', 'dim-011', 'fmt-003', 'fmt-004'],
          expectedBehavior: '2-3 Drive files (RFP, cost analysis) + 3-4 Jira epics, connections shown',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q8',
          query: 'What decisions has Legal (@james.miller) made in past 3 months?',
          patternTested: 'pat-011-C',
          dimensionsCrossed: ['dim-004', 'dim-011', 'dim-027', 'fmt-001', 'fmt-002'],
          expectedBehavior: '4-5 Confluence pages + Slack thread + Jira tasks, timeline with decision dates',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q9',
          query: 'What challenges is the Mobile team facing right now?',
          patternTested: 'pat-012-C',
          dimensionsCrossed: ['dim-024', 'dim-011', 'fmt-005', 'fmt-004', 'fmt-002'],
          expectedBehavior: 'Team members from Directory (4-5) + Jira issues/blockers (3-4) + Slack challenges',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q10',
          query: 'What action items came out of last month\'s architecture review?',
          patternTested: 'pat-014-C',
          dimensionsCrossed: ['dim-004', 'dim-011', 'dim-020', 'fmt-001', 'fmt-002', 'fmt-004'],
          expectedBehavior: 'Meeting notes + Slack thread (5-8 msgs) + Jira tasks (3-4), with owner/deadline/status',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q11',
          query: 'What caused the delay in the microservices migration?',
          patternTested: 'pat-018-R',
          dimensionsCrossed: ['dim-019', 'dim-023', 'dim-025', 'fmt-004', 'fmt-002', 'fmt-001'],
          expectedBehavior: 'Original timeline vs current + blockers (2-3) + Slack discussion + proposal, 84% confidence',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q12',
          query: 'Should we adopt the proposed API rate limiting strategy?',
          patternTested: 'pat-019-R',
          dimensionsCrossed: ['dim-024', 'dim-029', 'dim-025', 'fmt-001', 'fmt-002', 'fmt-004', 'fmt-003'],
          expectedBehavior: 'Current vs proposed + pros/cons discussion + cost analysis, medium confidence',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q13',
          query: 'What was the decision process for our data retention policy?',
          patternTested: 'pat-020-R',
          dimensionsCrossed: ['dim-003', 'dim-004', 'dim-019', 'dim-027', 'fmt-001', 'fmt-002', 'fmt-004'],
          expectedBehavior: 'Timeline: proposal → discussion → decision → implementation, with participants',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q14',
          query: 'Are there knowledge gaps in the team about our authentication system?',
          patternTested: 'pat-021-R',
          dimensionsCrossed: ['dim-024', 'dim-005', 'dim-029', 'dim-025', 'fmt-005', 'fmt-001', 'fmt-004'],
          expectedBehavior: 'Skills comparison (required vs actual) + question frequency, training recommendation',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q15',
          query: 'Summarize how we arrived at our current microservices architecture decision',
          patternTested: 'pat-022-R',
          dimensionsCrossed: ['dim-003', 'dim-004', 'dim-021', 'dim-025', 'fmt-001', 'fmt-002', 'fmt-004'],
          expectedBehavior: '12-month timeline with lessons learned, deployment/complexity trade-offs',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q16',
          query: 'What unresolved blockers exist from Q4 planning cycle?',
          patternTested: 'pat-023-R',
          dimensionsCrossed: ['dim-019', 'dim-023', 'dim-029', 'fmt-001', 'fmt-004', 'fmt-002'],
          expectedBehavior: 'Roadmap page + Jira blockers (4 issues) + Slack concerns (2 unresolved), actionable',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q17',
          query: 'Is the remote work policy being enforced uniformly across all offices?',
          patternTested: 'pat-025-R',
          dimensionsCrossed: ['dim-001', 'dim-004', 'dim-026', 'dim-025', 'fmt-001', 'fmt-002', 'fmt-005', 'fmt-003'],
          expectedBehavior: 'Policy vs practice comparison (60-90% compliance by office), recommend clarification, 79% confidence',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'rag-q18',
          query: 'Which Slack channels have the most recent activity about API performance issues?',
          patternTested: 'pat-011-C',
          dimensionsCrossed: ['dim-001', 'dim-011', 'dim-018', 'fmt-002'],
          expectedBehavior: '#eng-infrastructure (12 recent), #product-feedback (5), #oncall (8), linked to Jira incident',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q19',
          query: 'What expertise does our team have around containerization and Kubernetes?',
          patternTested: 'pat-016-C',
          dimensionsCrossed: ['dim-001', 'dim-010', 'dim-024', 'fmt-005', 'fmt-004'],
          expectedBehavior: '6 employees with K8s skills, activity mapping, knowledge island identification',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'rag-q20',
          query: 'Synthesize everything about our upcoming product launch strategy',
          patternTested: 'pat-015-C',
          dimensionsCrossed: ['dim-001', 'dim-011', 'dim-018', 'fmt-001', 'fmt-002', 'fmt-003', 'fmt-004', 'fmt-005'],
          expectedBehavior: 'Launch date, GTM regions, budget ($2.8M), risks, critical path, 80% information currency',
          difficulty: 'reasoning',
          tier: 'red',
        },
      ],
    },
    'faq-knowledge': {
      totalTests: 12,
      coveragePercent: 89,
      tests: [
        {
          id: 'faq-q1',
          query: 'How much vacation do I get?',
          patternTested: 'pat-001-S',
          dimensionsCrossed: ['dim-001', 'fmt-001', 'tool-search'],
          expectedBehavior: '20 days/year + 10 holidays, source: Benefits Guide (doc-001, Jan 2025)',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'faq-q2',
          query: 'How do I request time off?',
          patternTested: 'pat-002-S',
          dimensionsCrossed: ['dim-007', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Process steps from PTO Request Policy (doc-002), form link (doc-061)',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'faq-q3',
          query: 'What is the IT equipment budget for engineers?',
          patternTested: 'pat-003-S',
          dimensionsCrossed: ['dim-001', 'fmt-001', 'tool-search'],
          expectedBehavior: '$800 monitor/peripherals + $600 home office, source: IT Guides (doc-038)',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'faq-q4',
          query: 'How do I reset my password?',
          patternTested: 'pat-004-S',
          dimensionsCrossed: ['dim-007', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Step-by-step from IT guide (doc-045), include help desk contact',
          difficulty: 'simple',
          tier: 'green',
        },
        {
          id: 'faq-q5',
          query: 'What equipment can I request as a new remote engineer?',
          patternTested: 'pat-005-C',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Equipment budget (doc-038) + remote setup (doc-007) + onboarding (doc-019), high confidence (88%)',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'faq-q6',
          query: 'Do I get a parental leave stipend?',
          patternTested: 'pat-006-C',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Policy exists (doc-005) but lacks stipend detail, escalate to HR, medium confidence (62%)',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'faq-q7',
          query: 'Which health insurance plan should I choose?',
          patternTested: 'pat-007-C',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Multiple options in doc-004, clarify: role/family/preferences, schedule HR consultation, medium (71%)',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'faq-q8',
          query: 'How do I book travel and expense reimbursement?',
          patternTested: 'pat-008-C',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Synthesis: Travel (doc-042) + Reimbursement (doc-043) + Per Diem (doc-044), high confidence (86%)',
          difficulty: 'complex',
          tier: 'amber',
        },
        {
          id: 'faq-q9',
          query: 'Can I take 3 months off to travel and return to my role?',
          patternTested: 'pat-009-R',
          dimensionsCrossed: ['dim-006', 'dim-001', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Sabbatical (doc-006) + travel (doc-042) + custom scenario, escalate to HR, low confidence (54%)',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'faq-q10',
          query: 'I just moved countries; what do I need to know?',
          patternTested: 'pat-010-R',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Remote work (doc-007) + tax (doc-050) + health (doc-004) + travel (doc-042), escalate HR/Finance, medium (68%)',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'faq-q11',
          query: 'Old doc says vacation is 15 days; new doc says 20 days. Which is correct?',
          patternTested: 'pat-011-R',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Doc v2.1 (20 days, Jan 2025) supersedes v2.0 (15 days, Dec 2024), high confidence (94%)',
          difficulty: 'reasoning',
          tier: 'red',
        },
        {
          id: 'faq-q12',
          query: 'What is the escalation path if my manager won\'t approve my leave?',
          patternTested: 'pat-012-R',
          dimensionsCrossed: ['dim-001', 'dim-006', 'fmt-001', 'tool-search'],
          expectedBehavior: 'Leave Policy dispute process (doc-001) + HR escalation (doc-011) + form (doc-062), high confidence (89%)',
          difficulty: 'reasoning',
          tier: 'red',
        },
      ],
    },
  }

  return testDatabase[tileId] || null
}

/**
 * Get all synthetic test data for all tiles
 */
export function getAllSyntheticTestDataV3(): Record<string, TestCoverageV3> {
  const allTileIds = [
    'doc-intelligence',
    'saas-copilot',
    'research-comparison',
    'faq-knowledge',
  ]

  const result: Record<string, TestCoverageV3> = {}

  for (const tileId of allTileIds) {
    const data = getSyntheticTestDataV3(tileId)
    if (data) {
      result[tileId] = data
    }
  }

  return result
}

/**
 * Utility: get total test count across all tiles
 */
export function getTotalTestCountAcrossAllTiles(): number {
  const allData = getAllSyntheticTestDataV3()
  return Object.values(allData).reduce((sum, data) => sum + data.totalTests, 0)
}
