import type { DatasetConfig } from '@/store/types'

export const API_BASE = '/api/v1'

export const PREBUILT_DATASETS: DatasetConfig[] = [
  {
    id: 'telco-churn',
    name: 'Telco Customer Churn',
    description: 'Predict which telecom customers will leave based on usage patterns, billing, and service details.',
    domain: 'Telecom',
    taskType: 'classification',
    rows: 7043,
    features: 21,
    icon: 'phone',
    color: '#3b82f6',
    objectives: [
      {
        id: 'churn-predict',
        label: 'Predict Customer Churn',
        description: 'Identify customers likely to cancel their service so retention teams can intervene early.',
        targetColumn: 'Churn',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'churn-segment',
        label: 'Customer Segmentation',
        description: 'Discover natural customer groups to personalize marketing and reduce churn across segments.',
        targetColumn: 'Churn',
        metric: 'Silhouette Score',
        objectiveType: 'classification',
      },
      {
        id: 'churn-revenue',
        label: 'Revenue-at-Risk Analysis',
        description: 'Quantify the revenue impact of churn and prioritize high-value customers for retention.',
        targetColumn: 'Churn',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'credit-fraud',
    name: 'Credit Card Fraud Detection',
    description: 'Identify fraudulent transactions in a highly imbalanced dataset of credit card activity.',
    domain: 'Finance',
    taskType: 'classification',
    rows: 50000,
    features: 30,
    icon: 'shield',
    color: '#ef4444',
    objectives: [
      {
        id: 'fraud-detect',
        label: 'Detect Fraudulent Transactions',
        description: 'Flag suspicious transactions in real-time while minimizing false positives that block legitimate customers.',
        targetColumn: 'Class',
        metric: 'Precision-Recall AUC',
        objectiveType: 'classification',
      },
      {
        id: 'fraud-anomaly',
        label: 'Anomaly Pattern Discovery',
        description: 'Uncover novel fraud patterns and evolving attack vectors in transaction behavior.',
        targetColumn: 'Class',
        metric: 'Recall @ 1% FPR',
        objectiveType: 'anomaly-detection',
      },
      {
        id: 'fraud-risk',
        label: 'Transaction Risk Scoring',
        description: 'Assign a continuous risk score to each transaction for tiered fraud response workflows.',
        targetColumn: 'Class',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'store-demand',
    name: 'Retail Store Demand Forecast',
    description: 'Forecast product demand across multiple stores using historical sales and promotional data.',
    domain: 'Retail',
    taskType: 'regression',
    rows: 45000,
    features: 15,
    icon: 'trending-up',
    color: '#10b981',
    objectives: [
      {
        id: 'demand-forecast',
        label: 'Forecast Daily Demand',
        description: 'Predict next-day product demand per store to optimize inventory and reduce stockouts.',
        targetColumn: 'sales',
        metric: 'RMSE',
        objectiveType: 'regression',
      },
      {
        id: 'demand-promo',
        label: 'Promotion Impact Analysis',
        description: 'Quantify how promotions affect sales volume to optimize marketing spend and timing.',
        targetColumn: 'sales',
        metric: 'MAE',
        objectiveType: 'regression',
      },
      {
        id: 'demand-seasonal',
        label: 'Seasonal Trend Detection',
        description: 'Identify recurring seasonal patterns and trends to inform long-term inventory planning.',
        targetColumn: 'sales',
        metric: 'MAPE',
        objectiveType: 'regression',
      },
    ],
  },
  {
    id: 'patient-readmission',
    name: 'Patient Readmission Risk',
    description: 'Predict 30-day hospital readmission risk from patient demographics, diagnoses, and treatment history.',
    domain: 'Healthcare',
    taskType: 'classification',
    rows: 25000,
    features: 35,
    icon: 'heart-pulse',
    color: '#f59e0b',
    objectives: [
      {
        id: 'readmit-predict',
        label: 'Predict Readmission Risk',
        description: 'Identify patients at high risk of 30-day readmission so care teams can plan targeted follow-ups.',
        targetColumn: 'readmitted',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
      {
        id: 'readmit-factors',
        label: 'Risk Factor Analysis',
        description: 'Discover the key clinical and demographic factors driving readmission to inform care protocols.',
        targetColumn: 'readmitted',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'readmit-cost',
        label: 'Cost Optimization',
        description: 'Minimize readmission-related costs by prioritizing interventions for the highest-risk patients.',
        targetColumn: 'readmitted',
        metric: 'Precision @ 80% Recall',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'employee-attrition',
    name: 'Employee Attrition',
    description: 'Predict which employees are at risk of leaving using HR, compensation, satisfaction, and performance data.',
    domain: 'Human Resources',
    taskType: 'classification',
    rows: 14999,
    features: 35,
    icon: 'users',
    color: '#8b5cf6',
    objectives: [
      {
        id: 'attrition-predict',
        label: 'Predict Attrition Risk',
        description: 'Identify employees likely to leave so HR can intervene with targeted retention programs.',
        targetColumn: 'Attrition',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'attrition-drivers',
        label: 'Discover Attrition Drivers',
        description: 'Surface the key compensation, workload, and satisfaction factors driving employee turnover.',
        targetColumn: 'Attrition',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
      {
        id: 'attrition-segment',
        label: 'High-Risk Segment Analysis',
        description: 'Discover natural employee cohorts with elevated flight risk for targeted retention campaigns.',
        targetColumn: 'Attrition',
        metric: 'Silhouette Score',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'energy-consumption',
    name: 'Energy Consumption Forecast',
    description: 'Forecast hourly energy demand across grid zones using weather, time, and historical consumption data.',
    domain: 'Energy & Utilities',
    taskType: 'time-series',
    rows: 35040,
    features: 18,
    icon: 'zap',
    color: '#06b6d4',
    objectives: [
      {
        id: 'energy-forecast',
        label: 'Forecast Hourly Demand',
        description: 'Predict next-hour energy consumption per zone to optimize grid load balancing and reduce waste.',
        targetColumn: 'consumption_kwh',
        metric: 'MAPE',
        objectiveType: 'regression',
      },
      {
        id: 'energy-anomaly',
        label: 'Detect Consumption Anomalies',
        description: 'Identify abnormal consumption spikes that indicate equipment failure or unauthorized usage.',
        targetColumn: 'consumption_kwh',
        metric: 'Recall @ 5% FPR',
        objectiveType: 'anomaly-detection',
      },
      {
        id: 'energy-peak',
        label: 'Peak Demand Prediction',
        description: 'Predict daily peak demand windows to optimize pricing and capacity planning.',
        targetColumn: 'consumption_kwh',
        metric: 'RMSE',
        objectiveType: 'regression',
      },
    ],
  },
  {
    id: 'insurance-claims',
    name: 'Insurance Claims Fraud',
    description: 'Detect fraudulent insurance claims using policy, claimant, and incident data across auto and property lines.',
    domain: 'Insurance',
    taskType: 'classification',
    rows: 40000,
    features: 28,
    icon: 'file-search',
    color: '#ec4899',
    objectives: [
      {
        id: 'claims-fraud',
        label: 'Detect Fraudulent Claims',
        description: 'Flag suspicious claims for investigation before payout, minimizing false positives that delay legitimate claims.',
        targetColumn: 'fraud_reported',
        metric: 'Precision-Recall AUC',
        objectiveType: 'classification',
      },
      {
        id: 'claims-network',
        label: 'Fraud Network Discovery',
        description: 'Uncover organized fraud rings and staged accident networks through behavioral clustering.',
        targetColumn: 'fraud_reported',
        metric: 'Recall @ 2% FPR',
        objectiveType: 'anomaly-detection',
      },
      {
        id: 'claims-risk',
        label: 'Claim Risk Scoring',
        description: 'Assign a continuous fraud risk score to each claim for tiered investigation workflows.',
        targetColumn: 'fraud_reported',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'predictive-maintenance',
    name: 'Predictive Equipment Maintenance',
    description: 'Predict machine failures before they occur using IoT sensor readings, vibration data, and operational cycle counts.',
    domain: 'Manufacturing & IoT',
    taskType: 'classification',
    rows: 50000,
    features: 25,
    icon: 'settings',
    color: '#f97316',
    objectives: [
      {
        id: 'maint-predict',
        label: 'Predict Equipment Failure',
        description: 'Identify machines at risk of failure in the next 24 hours so maintenance teams can intervene before unplanned downtime.',
        targetColumn: 'failure',
        metric: 'Recall @ 95% Precision',
        objectiveType: 'classification',
      },
      {
        id: 'maint-anomaly',
        label: 'Detect Sensor Anomalies',
        description: 'Flag abnormal sensor readings that indicate wear, misalignment, or impending component failure.',
        targetColumn: 'failure',
        metric: 'Recall @ 5% FPR',
        objectiveType: 'anomaly-detection',
      },
      {
        id: 'maint-rul',
        label: 'Remaining Useful Life Estimation',
        description: 'Estimate how many operational cycles remain before a component reaches end-of-life to optimise maintenance scheduling.',
        targetColumn: 'rul_cycles',
        metric: 'RMSE',
        objectiveType: 'regression',
      },
    ],
  },

  // ── Logistics & Supply Chain ──────────────────────────────────────────────
  {
    id: 'logistics-delivery-delay',
    name: 'Delivery Delay Prediction',
    description: 'Predict whether a shipment will arrive late based on route, vehicle, weather, and package characteristics.',
    domain: 'Logistics & Supply Chain',
    taskType: 'classification',
    rows: 25000,
    features: 12,
    icon: 'truck',
    color: '#14b8a6',
    objectives: [
      {
        id: 'delay-predict',
        label: 'Predict Delivery Delays',
        description: 'Identify shipments likely to arrive late so operations teams can proactively reroute or notify customers.',
        targetColumn: 'is_delayed',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'delay-drivers',
        label: 'Discover Delay Drivers',
        description: 'Surface the key route, weather, and vehicle factors driving delivery delays to inform logistics planning.',
        targetColumn: 'is_delayed',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
      {
        id: 'delay-risk-scoring',
        label: 'Shipment Risk Scoring',
        description: 'Assign a continuous delay-risk score to each shipment for tiered SLA management workflows.',
        targetColumn: 'is_delayed',
        metric: 'Precision-Recall AUC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'logistics-freight-cost',
    name: 'Freight Cost Prediction',
    description: 'Predict the freight shipping cost (USD) for supply chain shipments based on route, cargo, and vendor characteristics.',
    domain: 'Logistics & Supply Chain',
    taskType: 'regression',
    rows: 5964,
    features: 12,
    icon: 'ship',
    color: '#6366f1',
    objectives: [
      {
        id: 'freight-estimate',
        label: 'Estimate Freight Cost',
        description: 'Predict the total shipping cost per shipment to power instant quote generation and budget forecasting.',
        targetColumn: 'freight_cost_usd',
        metric: 'RMSE',
        objectiveType: 'regression',
      },
      {
        id: 'freight-anomaly',
        label: 'Detect Cost Anomalies',
        description: 'Flag shipments with abnormally high or low freight costs relative to route and cargo characteristics.',
        targetColumn: 'freight_cost_usd',
        metric: 'MAE',
        objectiveType: 'regression',
      },
      {
        id: 'freight-optimise',
        label: 'Optimise Shipping Routes',
        description: 'Identify the most cost-effective shipment mode and vendor terms for each cargo profile.',
        targetColumn: 'freight_cost_usd',
        metric: 'MAPE',
        objectiveType: 'regression',
      },
    ],
  },
  {
    id: 'logistics-delivery-outcome',
    name: 'Delivery Outcome Classification',
    description: 'Classify shipments into four delivery outcomes — Late, On Time, Advance, or Canceled — before they happen.',
    domain: 'Logistics & Supply Chain',
    taskType: 'classification',
    rows: 180519,
    features: 31,
    icon: 'package-check',
    color: '#d946ef',
    objectives: [
      {
        id: 'outcome-classify',
        label: 'Classify Delivery Outcomes',
        description: 'Predict one of four delivery outcomes to trigger outcome-specific workflows before shipment arrives.',
        targetColumn: 'delivery_status',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'outcome-cancel-risk',
        label: 'Predict Cancellation Risk',
        description: 'Identify orders at high risk of cancellation so retention teams can intervene with proactive outreach.',
        targetColumn: 'delivery_status',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
      {
        id: 'outcome-segment',
        label: 'Outcome-Based Segmentation',
        description: 'Discover natural customer and order segments that drive different delivery outcomes across markets.',
        targetColumn: 'delivery_status',
        metric: 'Precision-Recall AUC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'logistics-demand-forecast',
    name: 'Logistics Demand Forecasting',
    description: 'Forecast daily logistics demand using historical patterns and operational signals like weather, traffic, and port congestion.',
    domain: 'Logistics & Supply Chain',
    taskType: 'time-series',
    rows: 1337,
    features: 11,
    icon: 'bar-chart-3',
    color: '#0ea5e9',
    objectives: [
      {
        id: 'demand-predict',
        label: 'Forecast Daily Demand',
        description: 'Predict next-day and next-week logistics demand to optimise fleet capacity and warehouse staffing.',
        targetColumn: 'avg_daily_demand',
        metric: 'MAPE',
        objectiveType: 'regression',
      },
      {
        id: 'demand-capacity',
        label: 'Capacity Planning',
        description: 'Forecast demand peaks and troughs to dynamically allocate fleet and warehouse resources.',
        targetColumn: 'avg_daily_demand',
        metric: 'RMSE',
        objectiveType: 'regression',
      },
      {
        id: 'demand-anomaly',
        label: 'Demand Anomaly Detection',
        description: 'Detect unusual demand spikes or drops driven by weather, port congestion, or supply chain disruptions.',
        targetColumn: 'avg_daily_demand',
        metric: 'MAE',
        objectiveType: 'regression',
      },
    ],
  },
]
