import type { DatasetConfig } from '@/store/types'

export const API_BASE = '/api/v1'

export const PREBUILT_DATASETS: DatasetConfig[] = [
  {
    id: 'telco-churn',
    name: 'Telco Customer Churn',
    description: 'Predict which telecom customers will leave based on usage patterns, billing, and service details.',
    domain: 'Telecom',
    taskType: 'classification',
    rows: 7043,
    features: 21,
    icon: 'phone',
    color: '#3b82f6',
    objectives: [
      {
        id: 'churn-predict',
        label: 'Predict Customer Churn',
        description: 'Identify customers likely to cancel their service so retention teams can intervene early.',
        targetColumn: 'Churn',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'churn-segment',
        label: 'Customer Segmentation',
        description: 'Discover natural customer groups to personalize marketing and reduce churn across segments.',
        targetColumn: 'Churn',
        metric: 'Silhouette Score',
        objectiveType: 'classification',
      },
      {
        id: 'churn-revenue',
        label: 'Revenue-at-Risk Analysis',
        description: 'Quantify the revenue impact of churn and prioritize high-value customers for retention.',
        targetColumn: 'Churn',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'credit-fraud',
    name: 'Credit Card Fraud Detection',
    description: 'Identify fraudulent transactions in a highly imbalanced dataset of credit card activity.',
    domain: 'Finance',
    taskType: 'classification',
    rows: 50000,
    features: 30,
    icon: 'shield',
    color: '#ef4444',
    objectives: [
      {
        id: 'fraud-detect',
        label: 'Detect Fraudulent Transactions',
        description: 'Flag suspicious transactions in real-time while minimizing false positives that block legitimate customers.',
        targetColumn: 'Class',
        metric: 'Precision-Recall AUC',
        objectiveType: 'classification',
      },
      {
        id: 'fraud-anomaly',
        label: 'Anomaly Pattern Discovery',
        description: 'Uncover novel fraud patterns and evolving attack vectors in transaction behavior.',
        targetColumn: 'Class',
        metric: 'Recall @ 1% FPR',
        objectiveType: 'anomaly-detection',
      },
      {
        id: 'fraud-risk',
        label: 'Transaction Risk Scoring',
        description: 'Assign a continuous risk score to each transaction for tiered fraud response workflows.',
        targetColumn: 'Class',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
    ],
  },
  {
    id: 'store-demand',
    name: 'Retail Store Demand Forecast',
    description: 'Forecast product demand across multiple stores using historical sales and promotional data.',
    domain: 'Retail',
    taskType: 'regression',
    rows: 45000,
    features: 15,
    icon: 'trending-up',
    color: '#10b981',
    objectives: [
      {
        id: 'demand-forecast',
        label: 'Forecast Daily Demand',
        description: 'Predict next-day product demand per store to optimize inventory and reduce stockouts.',
        targetColumn: 'sales',
        metric: 'RMSE',
        objectiveType: 'regression',
      },
      {
        id: 'demand-promo',
        label: 'Promotion Impact Analysis',
        description: 'Quantify how promotions affect sales volume to optimize marketing spend and timing.',
        targetColumn: 'sales',
        metric: 'MAE',
        objectiveType: 'regression',
      },
      {
        id: 'demand-seasonal',
        label: 'Seasonal Trend Detection',
        description: 'Identify recurring seasonal patterns and trends to inform long-term inventory planning.',
        targetColumn: 'sales',
        metric: 'MAPE',
        objectiveType: 'regression',
      },
    ],
  },
  {
    id: 'patient-readmission',
    name: 'Patient Readmission Risk',
    description: 'Predict 30-day hospital readmission risk from patient demographics, diagnoses, and treatment history.',
    domain: 'Healthcare',
    taskType: 'classification',
    rows: 25000,
    features: 35,
    icon: 'heart-pulse',
    color: '#f59e0b',
    objectives: [
      {
        id: 'readmit-predict',
        label: 'Predict Readmission Risk',
        description: 'Identify patients at high risk of 30-day readmission so care teams can plan targeted follow-ups.',
        targetColumn: 'readmitted',
        metric: 'AUC-ROC',
        objectiveType: 'classification',
      },
      {
        id: 'readmit-factors',
        label: 'Risk Factor Analysis',
        description: 'Discover the key clinical and demographic factors driving readmission to inform care protocols.',
        targetColumn: 'readmitted',
        metric: 'F1 Score',
        objectiveType: 'classification',
      },
      {
        id: 'readmit-cost',
        label: 'Cost Optimization',
        description: 'Minimize readmission-related costs by prioritizing interventions for the highest-risk patients.',
        targetColumn: 'readmitted',
        metric: 'Precision @ 80% Recall',
        objectiveType: 'classification',
      },
    ],
  },
]
